# Generated by Django 5.2.1 on 2025-07-20 22:45

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Categoría')),
            ],
            options={
                'verbose_name': 'Categoría de Gasto',
                'verbose_name_plural': 'Categorías de Gastos',
            },
        ),
        migrations.CreateModel(
            name='ConceptoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_concepto', models.CharField(max_length=200, verbose_name='Nombre Específico del Concepto')),
                ('descripcion_detallada', models.TextField(blank=True, null=True, verbose_name='Descripción Detallada')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Estándar del Concepto')),
                ('fecha_vencimiento_general', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento General (Opcional)')),
                ('automatico', models.BooleanField(default=False, verbose_name='¿Generar automáticamente al registrar estudiante?')),
                ('es_pago_inscripcion', models.BooleanField(default=False, help_text='Marcar solo para el único concepto que se usará para cobrar la inscripción/postulación.', verbose_name='¿Es el concepto de pago de Inscripción?')),
                ('permite_mora', models.BooleanField(default=False, help_text='Marcar si este concepto debe generar intereses si se vence.', verbose_name='¿Permite generar mora?')),
                ('porcentaje_mora_mensual', models.DecimalField(blank=True, decimal_places=2, help_text="Ej: 2.5 para 2.5%. Solo aplica si se marca 'Permite generar mora'.", max_digits=5, null=True, verbose_name='Porcentaje de Mora Mensual (%)')),
                ('es_pago_matricula', models.BooleanField(default=False, help_text='Marcar solo para el único concepto que se usará para cobrar la matrícula oficial.', verbose_name='¿Es el concepto de pago de Matrícula?')),
                ('es_solicitable_por_egresado', models.BooleanField(default=False, help_text='Marcar si este concepto debe aparecer en la lista de documentos que un egresado puede solicitar y pagar.', verbose_name='¿Es solicitable desde el Portal de Egresados?')),
            ],
            options={
                'verbose_name': 'Concepto de Pago',
                'verbose_name_plural': 'Conceptos de Pago',
                'ordering': ['periodo_academico_aplicable', 'nombre_concepto'],
                'permissions': [],
            },
        ),
        migrations.CreateModel(
            name='ConsecutivoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=50, verbose_name='Tipo de Documento')),
                ('siguiente_numero', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código PUC')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Cuenta')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('GASTO', 'Gasto'), ('ACTIVO', 'Activo'), ('PASIVO', 'Pasivo'), ('PATRIMONIO', 'Patrimonio')], max_length=20, verbose_name='Tipo de Cuenta')),
            ],
            options={
                'verbose_name': 'Cuenta Contable (PUC)',
                'verbose_name_plural': 'Cuentas Contables (PUC)',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='CuentaPorCobrarEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_asignado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Monto Asignado al Estudiante')),
                ('fecha_vencimiento_especifica', models.DateField(verbose_name='Fecha de Vencimiento para este Estudiante')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO_PARCIAL', 'Pagado Parcialmente'), ('PAGADO', 'Pagado Completamente'), ('VENCIDO', 'Vencido'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=20, verbose_name='Estado de la Cuenta')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación de la Cuenta')),
                ('ultima_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('observaciones_internas', models.TextField(blank=True, null=True, verbose_name='Observaciones Internas (Admin)')),
                ('mercadopago_preference_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID de Preferencia (Mercado Pago)')),
                ('referencia_pago_externo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Referencia de Pago Externo')),
                ('numero_documento', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Número de Factura')),
                ('año', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año del Cobro')),
                ('mes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Mes del Cobro (2-11)')),
            ],
            options={
                'verbose_name': 'Cuenta por Cobrar a Estudiante',
                'verbose_name_plural': 'Cuentas por Cobrar a Estudiantes',
                'ordering': ['-fecha_vencimiento_especifica'],
                'permissions': [('ver_cuentas_por_cobrar', 'Puede ver el listado de cuentas por cobrar')],
            },
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Descuento o Beca')),
                ('tipo', models.CharField(choices=[('PORCENTAJE', 'Porcentaje (%)'), ('VALOR_FIJO', 'Valor Fijo ($)')], default='PORCENTAJE', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, help_text='El porcentaje (ej: 10.00 para 10%) o el valor fijo en pesos.', max_digits=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Descuento o Beca',
                'verbose_name_plural': 'Descuentos y Becas',
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción del Gasto')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_gasto', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del Gasto')),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes_gastos/', verbose_name='Comprobante (Factura/Recibo)')),
                ('numero_documento', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Número de Comprobante')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-fecha_gasto'],
            },
        ),
        migrations.CreateModel(
            name='InstitucionEducativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Institución Educativa')),
                ('nit', models.CharField(max_length=20, unique=True, verbose_name='NIT')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico de Contacto')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo')),
                ('texto_aprobacion', models.CharField(blank=True, default='Aprobado por Secretaria de Educación Departamental', max_length=255, verbose_name='Texto de Aprobación')),
                ('texto_resolucion', models.TextField(blank=True, default='Resolución Ampliación Nivel Básica Primaria\nN°3161 del 18 de octubre de 2022', verbose_name='Texto de Resolución(es)')),
                ('codigo_dane', models.CharField(blank=True, max_length=50, verbose_name='Código de Identificación DANE')),
                ('ciudad_departamento', models.CharField(blank=True, default='Sabanalarga - Atlántico', max_length=150, verbose_name='Ciudad y Departamento')),
                ('nombre_rectora', models.CharField(blank=True, max_length=150, verbose_name='Nombre Completo del Rector(a)')),
                ('firma_rectora', models.ImageField(blank=True, null=True, upload_to='firmas/', verbose_name='Firma del Rector(a) (Imagen)')),
                ('eslogan', models.CharField(blank=True, max_length=255, null=True, verbose_name='Eslogan (Opcional)')),
                ('cuenta_bancaria', models.CharField(blank=True, help_text='Ej: Ahorros Bancolombia 123-456789-00', max_length=255, null=True, verbose_name='Información Cuenta Bancaria')),
                ('pagos_digitales', models.CharField(blank=True, help_text='Ej: Nequi 300-123-4567', max_length=255, null=True, verbose_name='Información Nequi/Daviplata')),
                ('nota_minima_aprobacion', models.DecimalField(decimal_places=2, default=Decimal('3.0'), help_text='La nota que un estudiante debe alcanzar o superar para aprobar (ej: 3.0, 3.5).', max_digits=3, verbose_name='Nota Mínima para Aprobar')),
                ('escala_valorativa_texto', models.CharField(blank=True, default='Sup = Superior, Alt = Alto, Bas = Básico, Baj = Bajo', max_length=255, verbose_name='Texto de la Escala Valorativa')),
                ('google_calendar_embed_code', models.TextField(blank=True, null=True, verbose_name='Código para insertar Google Calendar')),
                ('mp_public_key_test', models.CharField(blank=True, max_length=255, null=True, verbose_name='Public Key de Prueba (Mercado Pago)')),
                ('mp_access_token_test', models.CharField(blank=True, max_length=255, null=True, verbose_name='Access Token de Prueba (Mercado Pago)')),
                ('mp_public_key_prod', models.CharField(blank=True, max_length=255, null=True, verbose_name='Public Key de Producción (Mercado Pago)')),
                ('mp_access_token_prod', models.CharField(blank=True, max_length=255, null=True, verbose_name='Access Token de Producción (Mercado Pago)')),
                ('mp_modo_produccion', models.BooleanField(default=False, help_text='Si está desmarcado, se usarán las credenciales de prueba.', verbose_name='¿Activar modo producción para Mercado Pago?')),
                ('email_host_user', models.EmailField(blank=True, help_text='Ej: notificaciones@micolegio.com', max_length=255, null=True, verbose_name='Correo para Envío de Notificaciones (SMTP User)')),
                ('email_host_password', models.CharField(blank=True, help_text='¡IMPORTANTE! Usa una contraseña de aplicación generada, no tu contraseña principal.', max_length=255, null=True, verbose_name='Contraseña de Aplicación (SMTP Password)')),
                ('email_host', models.CharField(blank=True, default='smtp.gmail.com', max_length=255, null=True, verbose_name='Servidor SMTP')),
                ('email_port', models.PositiveIntegerField(blank=True, default=587, null=True, verbose_name='Puerto SMTP')),
                ('email_use_tls', models.BooleanField(default=True, verbose_name='¿Usar TLS?')),
                ('activa', models.BooleanField(default=True, help_text='Desmarca esta casilla para bloquear el acceso de todos los usuarios de esta institución (excepto super-admins).', verbose_name='Institución Activa')),
                ('tarifa_mensual_plataforma', models.DecimalField(decimal_places=2, default=0, help_text='El valor que esta institución paga mensualmente por usar HALU.', max_digits=10, verbose_name='Tarifa Mensual de la Plataforma ($)')),
                ('comision_por_transaccion_porcentaje', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de comisión a cobrar sobre cada pago procesado por la pasarela. Ej: 1.5 para 1.5%', max_digits=5, verbose_name='Comisión por Transacción (%)')),
            ],
            options={
                'verbose_name': 'Institución Educativa',
                'verbose_name_plural': 'Instituciones Educativas',
                'permissions': [('can_manage_institutions', 'Puede gestionar instituciones educativas')],
            },
        ),
        migrations.CreateModel(
            name='ItemCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Ítem de Cuenta',
                'verbose_name_plural': 'Ítems de Cuenta',
            },
        ),
        migrations.CreateModel(
            name='PagoRegistrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del Pago')),
                ('valor_pagado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Pagado')),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('TARJETA_DEBITO', 'Tarjeta de Débito'), ('TARJETA_CREDITO', 'Tarjeta de Crédito'), ('PSE', 'PSE (Pagos Seguros en Línea)'), ('MERCADO_PAGO', 'Mercado Pago'), ('OTRO', 'Otro')], max_length=20, verbose_name='Método de Pago')),
                ('referencia_transaccion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia de la Transacción')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación del Pago')),
                ('fecha_registro_sistema', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro en Sistema')),
                ('numero_documento', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Número de Recibo')),
            ],
            options={
                'verbose_name': 'Pago Registrado',
                'verbose_name_plural': 'Pagos Registrados',
                'ordering': ['-fecha_registro_sistema'],
                'permissions': [('puede_editar_pago', 'Puede editar pagos registrados'), ('puede_eliminar_pago', 'Puede eliminar pagos registrados')],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre o Razón Social')),
                ('nit_o_cedula', models.CharField(blank=True, max_length=20, null=True, verbose_name='NIT o Cédula')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='TipoConceptoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Tipo de Concepto')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción Adicional')),
            ],
            options={
                'verbose_name': 'Tipo de Concepto de Pago',
                'verbose_name_plural': 'Tipos de Conceptos de Pago',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Tipo de Gasto')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción Adicional')),
            ],
            options={
                'verbose_name': 'Tipo de Gasto',
                'verbose_name_plural': 'Tipos de Gastos',
                'ordering': ['nombre'],
            },
        ),
    ]
