# Generated by Django 5.2.1 on 2025-07-20 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admisiones', '0003_initial'),
        ('finanzas', '0001_initial'),
        ('gestion_academica', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptopago',
            name='nivel_escolaridad',
            field=models.ForeignKey(blank=True, help_text='Asigna esto si el valor es solo para un nivel (ej: Matrícula Primaria).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_academica.nivelescolaridad', verbose_name='Nivel de Escolaridad (si aplica)'),
        ),
        migrations.AddField(
            model_name='conceptopago',
            name='periodo_academico_aplicable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conceptos_pago', to='gestion_academica.periodoacademico', verbose_name='Periodo Académico Aplicable (Opcional)'),
        ),
        migrations.AddField(
            model_name='conceptopago',
            name='cuenta_contable',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'INGRESO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.cuentacontable', verbose_name='Cuenta Contable (PUC)'),
        ),
        migrations.AddField(
            model_name='categoriagasto',
            name='cuenta_contable',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'GASTO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.cuentacontable', verbose_name='Cuenta Contable (PUC)'),
        ),
        migrations.AddField(
            model_name='cuentaporcobrarestudiante',
            name='aspirante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_por_cobrar_aspirante', to='admisiones.aspirante'),
        ),
        migrations.AddField(
            model_name='cuentaporcobrarestudiante',
            name='concepto_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instancias_cobro', to='finanzas.conceptopago', verbose_name='Concepto de Pago'),
        ),
        migrations.AddField(
            model_name='cuentaporcobrarestudiante',
            name='estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_por_cobrar', to='gestion_academica.estudiante'),
        ),
        migrations.AddField(
            model_name='descuento',
            name='conceptos_aplicables',
            field=models.ManyToManyField(blank=True, to='finanzas.conceptopago'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finanzas.categoriagasto', verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='institucioneducativa',
            name='aspirante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_por_cobrar_estudiante', to='admisiones.aspirante'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='institucion',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='finanzas.institucioneducativa'),
        ),
        migrations.AddField(
            model_name='descuento',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzas.institucioneducativa'),
        ),
        migrations.AddField(
            model_name='cuentaporcobrarestudiante',
            name='institucion',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='finanzas.institucioneducativa'),
        ),
        migrations.AddField(
            model_name='consecutivodocumento',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzas.institucioneducativa'),
        ),
        migrations.AddField(
            model_name='conceptopago',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzas.institucioneducativa', verbose_name='Institución'),
        ),
        migrations.AddField(
            model_name='categoriagasto',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzas.institucioneducativa'),
        ),
        migrations.AddField(
            model_name='itemcuenta',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finanzas.cuentaporcobrarestudiante'),
        ),
        migrations.AddField(
            model_name='pagoregistrado',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='finanzas.cuentaporcobrarestudiante', verbose_name='Cuenta Asociada'),
        ),
        migrations.AddField(
            model_name='pagoregistrado',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_realizados', to='gestion_academica.estudiante', verbose_name='Estudiante que Paga'),
        ),
        migrations.AddField(
            model_name='pagoregistrado',
            name='institucion',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='finanzas.institucioneducativa'),
        ),
        migrations.AddField(
            model_name='pagoregistrado',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_registrados_por_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por (Admin)'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzas.institucioneducativa'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.proveedor'),
        ),
        migrations.AddField(
            model_name='tipoconceptopago',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzas.institucioneducativa', verbose_name='Institución'),
        ),
        migrations.AddField(
            model_name='conceptopago',
            name='tipo_concepto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finanzas.tipoconceptopago', verbose_name='Tipo de Concepto'),
        ),
        migrations.AddField(
            model_name='tipogasto',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzas.institucioneducativa', verbose_name='Institución'),
        ),
        migrations.AddField(
            model_name='categoriagasto',
            name='tipo_gasto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorias', to='finanzas.tipogasto', verbose_name='Tipo de Gasto al que Pertenece'),
        ),
        migrations.AlterUniqueTogether(
            name='cuentaporcobrarestudiante',
            unique_together={('estudiante', 'concepto_pago', 'año', 'mes')},
        ),
        migrations.AlterUniqueTogether(
            name='consecutivodocumento',
            unique_together={('institucion', 'tipo_documento')},
        ),
        migrations.AlterUniqueTogether(
            name='tipoconceptopago',
            unique_together={('nombre', 'institucion')},
        ),
        migrations.AlterUniqueTogether(
            name='conceptopago',
            unique_together={('nombre_concepto', 'tipo_concepto', 'institucion')},
        ),
        migrations.AlterUniqueTogether(
            name='tipogasto',
            unique_together={('nombre', 'institucion')},
        ),
        migrations.AlterUniqueTogether(
            name='categoriagasto',
            unique_together={('nombre', 'tipo_gasto', 'institucion')},
        ),
    ]
