# Generated by Django 5.2.1 on 2025-07-21 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentacontable',
            name='institucion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='finanzas.institucioneducativa', verbose_name='Institución'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='cuentacontable',
            unique_together={('codigo', 'institucion')},
        ),
    ]
