# Generated by Django 5.2.1 on 2026-05-13 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0007_auditoriaexportacioncontable'),
    ]

    operations = [
        migrations.CreateModel(
            name='LlamadaMercadoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('preference.create', 'Crear preferencia'), ('payment.get', 'Consultar pago'), ('payment.search', 'Buscar pagos'), ('otro', 'Otro')], max_length=32, verbose_name='Acción')),
                ('external_reference', models.CharField(blank=True, max_length=128)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('intento', models.PositiveSmallIntegerField(default=1)),
                ('latencia_ms', models.PositiveIntegerField(default=0)),
                ('estado_http', models.PositiveSmallIntegerField(default=0)),
                ('exito', models.BooleanField(default=False)),
                ('error_mensaje', models.TextField(blank=True)),
                ('request_resumen', models.JSONField(blank=True, default=dict)),
                ('response_resumen', models.JSONField(blank=True, default=dict)),
                ('modo_produccion', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llamadas_mercadopago', to='finanzas.cuentaporcobrarestudiante')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llamadas_mercadopago', to='finanzas.institucioneducativa')),
            ],
            options={
                'verbose_name': 'Llamada Mercado Pago',
                'verbose_name_plural': 'Llamadas Mercado Pago',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['institucion', '-fecha'], name='finanzas_ll_institu_99517e_idx'), models.Index(fields=['accion', 'exito'], name='finanzas_ll_accion_7e9997_idx'), models.Index(fields=['external_reference'], name='finanzas_ll_externa_134328_idx')],
            },
        ),
        migrations.CreateModel(
            name='WebhookEventoMercadoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_id', models.CharField(help_text='ID del recurso (payment/merchant_order) notificado.', max_length=64, verbose_name='data.id de Mercado Pago')),
                ('tipo', models.CharField(blank=True, help_text='Campo `type` del payload (payment, merchant_order, etc.).', max_length=32, verbose_name='type')),
                ('payload_hash', models.CharField(help_text='Hash del body bruto: detecta reenvíos exactos del proveedor.', max_length=64, verbose_name='SHA-256 del payload')),
                ('x_request_id', models.CharField(blank=True, max_length=128)),
                ('x_signature', models.CharField(blank=True, max_length=255)),
                ('firma_valida', models.BooleanField(default=False)),
                ('payload_resumen', models.JSONField(blank=True, default=dict, help_text='Subset auditable del payload (sin datos sensibles).', verbose_name='Resumen del payload')),
                ('estado_http_devuelto', models.PositiveSmallIntegerField(default=0)),
                ('procesado_ok', models.BooleanField(default=False)),
                ('error_mensaje', models.TextField(blank=True)),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True)),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True)),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_eventos', to='finanzas.cuentaporcobrarestudiante')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks_mercadopago', to='finanzas.institucioneducativa', verbose_name='Institución')),
                ('pago_registrado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_eventos', to='finanzas.pagoregistrado')),
            ],
            options={
                'verbose_name': 'Evento webhook Mercado Pago',
                'verbose_name_plural': 'Eventos webhook Mercado Pago',
                'ordering': ['-fecha_recepcion'],
                'indexes': [models.Index(fields=['institucion', '-fecha_recepcion'], name='finanzas_we_institu_f61ba5_idx'), models.Index(fields=['data_id'], name='finanzas_we_data_id_4b40b2_idx'), models.Index(fields=['procesado_ok'], name='finanzas_we_procesa_93db4f_idx')],
                'constraints': [models.UniqueConstraint(fields=('institucion', 'data_id', 'payload_hash'), name='webhook_mp_unico_por_inst_dataid_hash')],
            },
        ),
    ]
