# Generated by Django 5.2.1 on 2026-05-13 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0010_institucion_bloqueo_mora'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EjecucionHealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iniciado_at', models.DateTimeField(auto_now_add=True, verbose_name='Iniciado en')),
                ('terminado_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminado en')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EJECUTANDO', 'Ejecutando'), ('OK', 'OK'), ('WARN', 'Con advertencias'), ('ERROR', 'Con errores'), ('FALLIDO', 'Fallido (excepción interna)')], default='PENDIENTE', max_length=20)),
                ('task_id', models.CharField(blank=True, default='', help_text='ID de la tarea Celery asociada.', max_length=255)),
                ('errores_count', models.PositiveIntegerField(default=0)),
                ('warnings_count', models.PositiveIntegerField(default=0)),
                ('pasos_completados', models.PositiveSmallIntegerField(default=0)),
                ('eventos', models.JSONField(blank=True, default=list, help_text='Lista de eventos generados por el health-check (cada uno con nivel/mensaje/paso).')),
                ('error_excepcion', models.TextField(blank=True, help_text='Si la tarea falló por excepción interna, traceback resumido.')),
                ('iniciado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ejecuciones_healthcheck', to=settings.AUTH_USER_MODEL, verbose_name='Iniciado por')),
                ('institucion_filtro', models.ForeignKey(blank=True, help_text='Si se especifica, el check se restringe a esta institución.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ejecuciones_healthcheck', to='finanzas.institucioneducativa', verbose_name='Filtro de institución')),
            ],
            options={
                'verbose_name': 'Ejecución de Health-Check',
                'verbose_name_plural': 'Ejecuciones de Health-Check',
                'ordering': ['-iniciado_at'],
                'indexes': [models.Index(fields=['-iniciado_at'], name='finanzas_ej_iniciad_925675_idx'), models.Index(fields=['estado'], name='finanzas_ej_estado_f4d2fa_idx')],
            },
        ),
    ]
