# Generated by Django 5.2.1 on 2026-05-25 00:01

import utils.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0011_ejecucionhealthcheck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucioneducativa',
            name='email_host_password',
            field=utils.encrypted_fields.EncryptedCharField(blank=True, help_text='¡IMPORTANTE! Usa una contraseña de aplicación generada, no tu contraseña principal.', null=True, verbose_name='Contraseña de Aplicación (SMTP Password)'),
        ),
        migrations.AlterField(
            model_name='institucioneducativa',
            name='google_api_key',
            field=utils.encrypted_fields.EncryptedCharField(default='', help_text='Clave de la API de Google AI / Gemini para esta institución (obligatoria para funciones de IA).', verbose_name='Google API Key (Gemini)'),
        ),
        migrations.AlterField(
            model_name='institucioneducativa',
            name='mp_access_token_prod',
            field=utils.encrypted_fields.EncryptedCharField(blank=True, null=True, verbose_name='Access Token de Producción (Mercado Pago)'),
        ),
        migrations.AlterField(
            model_name='institucioneducativa',
            name='mp_access_token_test',
            field=utils.encrypted_fields.EncryptedCharField(blank=True, null=True, verbose_name='Access Token de Prueba (Mercado Pago)'),
        ),
    ]
