# Generated by Django 5.2.1 on 2026-05-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0012_encrypt_credenciales_institucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoregistrado',
            name='anulado',
            field=models.BooleanField(default=False, verbose_name='Anulado'),
        ),
        migrations.AddField(
            model_name='pagoregistrado',
            name='anulado_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de anulación'),
        ),
        migrations.AddField(
            model_name='pagoregistrado',
            name='anulado_motivo',
            field=models.CharField(blank=True, max_length=255, verbose_name='Motivo de anulación'),
        ),
    ]
