# Generated by Django 5.2.1 on 2026-06-01 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0013_pagoregistrado_anulado_pagoregistrado_anulado_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucioneducativa',
            name='tipo_institucion',
            field=models.CharField(choices=[('privado', 'Privado'), ('publico', 'Público')], default='privado', help_text='Privado: cobra mensualidades. Público: financiado por el Estado, sin cobros a estudiantes.', max_length=10, verbose_name='Tipo de Institución'),
        ),
    ]
