# Generated by Django 5.2.1 on 2026-06-01 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0014_add_tipo_institucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucioneducativa',
            name='es_bilingue',
            field=models.BooleanField(default=False, help_text='Activa campos de segundo idioma en materias y mallas curriculares.', verbose_name='Institución Bilingüe / Multiidioma'),
        ),
        migrations.AddField(
            model_name='institucioneducativa',
            name='idioma_secundario',
            field=models.CharField(blank=True, choices=[('en', 'Inglés'), ('fr', 'Francés'), ('pt', 'Portugués'), ('de', 'Alemán'), ('zh', 'Mandarín')], default='en', help_text='Idioma en que se dictan las materias bilingües (por defecto inglés).', max_length=5, verbose_name='Idioma Secundario de Instrucción'),
        ),
    ]
