# Generated by Django 5.2.15 on 2026-06-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0016_brevo_per_institucion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institucioneducativa",
            name="brevo_sender_email",
            field=models.EmailField(
                blank=True,
                help_text="Email verificado en Brevo desde el que se envían los correos. Ej: notificaciones@micolegio.com",
                max_length=255,
                null=True,
                verbose_name="Email Remitente Brevo",
            ),
        ),
        migrations.AlterField(
            model_name="institucioneducativa",
            name="brevo_sender_name",
            field=models.CharField(
                blank=True,
                help_text="Nombre que aparece como remitente. Ej: 'Colegio San José'. Si no se configura, se usa el nombre de la institución.",
                max_length=100,
                null=True,
                verbose_name="Nombre Remitente Brevo",
            ),
        ),
    ]
