# Generated by Django 5.2.15 on 2026-06-18 21:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0019_encrypt_mp_webhook_secret"),
        ("gestion_academica", "0041_caracterizacionestudiante"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="cuentacontable",
            name="codigo",
            field=models.CharField(max_length=20, verbose_name="Código PUC"),
        ),
        migrations.AddConstraint(
            model_name="pagoregistrado",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("referencia_transaccion__isnull", False),
                    models.Q(("referencia_transaccion", ""), _negated=True),
                ),
                fields=("referencia_transaccion",),
                name="unique_referencia_transaccion_non_empty",
            ),
        ),
    ]
