# Generated by Django 5.2.15 on 2026-06-18 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0020_fix_db_constraints"),
        ("gestion_academica", "0041_caracterizacionestudiante"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cuentaporcobrarestudiante",
            name="fecha_castigo",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de castigo"
            ),
        ),
        migrations.AddField(
            model_name="cuentaporcobrarestudiante",
            name="motivo_castigo",
            field=models.TextField(
                blank=True, null=True, verbose_name="Motivo de castigo (incobrable)"
            ),
        ),
        migrations.AlterField(
            model_name="cuentaporcobrarestudiante",
            name="estado",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente"),
                    ("PAGADO_PARCIAL", "Pagado Parcialmente"),
                    ("PAGADO", "Pagado Completamente"),
                    ("VENCIDO", "Vencido"),
                    ("ANULADO", "Anulado"),
                    ("CASTIGADA", "Castigada (Incobrable)"),
                ],
                default="PENDIENTE",
                max_length=20,
                verbose_name="Estado de la Cuenta",
            ),
        ),
        migrations.CreateModel(
            name="AuditoriaAccionPago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            ("EDICION", "Edición de pago"),
                            ("ELIMINACION", "Eliminación de pago"),
                            ("ANULACION", "Anulación contable (NC)"),
                            ("CASTIGO", "Castigo de cartera"),
                        ],
                        max_length=20,
                        verbose_name="Acción",
                    ),
                ),
                ("pago_id", models.IntegerField(verbose_name="ID del pago afectado")),
                (
                    "cuenta_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID cuenta por cobrar"
                    ),
                ),
                (
                    "valor_pago",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("metodo_pago", models.CharField(blank=True, max_length=20)),
                (
                    "detalle",
                    models.TextField(blank=True, verbose_name="Detalle del cambio"),
                ),
                (
                    "datos_anteriores",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Estado anterior (JSON)"
                    ),
                ),
                (
                    "fecha",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha y hora"
                    ),
                ),
                (
                    "estudiante",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="gestion_academica.estudiante",
                        verbose_name="Estudiante",
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finanzas.institucioneducativa",
                        verbose_name="Institución",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario que realizó la acción",
                    ),
                ),
            ],
            options={
                "verbose_name": "Auditoría de Acción sobre Pago",
                "verbose_name_plural": "Auditorías de Acciones sobre Pagos",
                "ordering": ["-fecha"],
            },
        ),
    ]
