# Generated by Django 5.2.1 on 2026-08-14 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0029_consumo_ia_y_tope"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModuloPlataforma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.SlugField(
                        help_text="Identificador interno del módulo, ej. 'admisiones' (sin espacios).",
                        max_length=40,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=80, verbose_name="Nombre visible"),
                ),
                (
                    "descripcion",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Descripción"
                    ),
                ),
                (
                    "icono",
                    models.CharField(
                        blank=True,
                        help_text="Clase de Bootstrap Icons, ej. 'bi-mortarboard'.",
                        max_length=40,
                        verbose_name="Ícono",
                    ),
                ),
                (
                    "prefijo_url",
                    models.CharField(
                        blank=True,
                        help_text="Prefijo de URL del módulo, ej. '/admisiones/'. Si se define, el acceso a esa ruta se bloquea para las instituciones que no tengan el módulo contratado. Déjalo vacío si el módulo no se bloquea por URL.",
                        max_length=80,
                        verbose_name="Prefijo de URL",
                    ),
                ),
                (
                    "orden",
                    models.PositiveSmallIntegerField(default=100, verbose_name="Orden"),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Si se desactiva, el módulo deja de ofrecerse a TODAS las instituciones.",
                        verbose_name="Activo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Módulo de la plataforma",
                "verbose_name_plural": "Módulos de la plataforma",
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.AddField(
            model_name="institucioneducativa",
            name="modulos_contratados",
            field=models.ManyToManyField(
                blank=True,
                help_text="Marca los módulos que este colegio compró en su plan. Los módulos que NO estén marcados se ocultan del menú y se bloquean para los usuarios de esta institución (el superusuario siempre los ve).",
                related_name="instituciones",
                to="finanzas.moduloplataforma",
                verbose_name="Módulos contratados (plan)",
            ),
        ),
    ]
