# Generated by Django 5.2.1 on 2026-08-15 03:14

from django.db import migrations, models


def backfill_idiomas(apps, schema_editor):
    """Compatibilidad: los colegios que ya eran bilingües con un idioma_secundario
    traducible (inglés/francés) heredan ese idioma como contratado, para que su
    selector siga funcionando igual que antes."""
    Inst = apps.get_model("finanzas", "InstitucionEducativa")
    disponibles = {"en", "fr"}
    for inst in Inst.objects.all():
        if not inst.idiomas_contratados and inst.es_bilingue and inst.idioma_secundario in disponibles:
            inst.idiomas_contratados = [inst.idioma_secundario]
            inst.save(update_fields=["idiomas_contratados"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0032_seed_mas_modulos"),
    ]

    operations = [
        migrations.AddField(
            model_name="institucioneducativa",
            name="idiomas_contratados",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Idiomas (además del español, que siempre está) en los que este colegio puede ver la plataforma. Se muestran en el selector de idioma de cada usuario.",
                verbose_name="Idiomas de interfaz contratados",
            ),
        ),
        migrations.RunPython(backfill_idiomas, noop),
    ]
