# Generated by Django 5.2.17 on 2026-09-21 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0036_seed_modulo_presupuesto"),
        ("gestion_academica", "0100_backfill_permisos_grupos_0039"),
    ]

    operations = [
        migrations.AddField(
            model_name="institucioneducativa",
            name="codigo_convenio_bancario",
            field=models.CharField(
                blank=True,
                help_text="Los 13 dígitos que tu banco (Bancolombia u otro con recaudo referenciado GS1) te asigna al abrir ese servicio. Sin esto, los recibos con código de barras para pagar en el banco no se generan — la facturación masiva sigue funcionando igual.",
                max_length=13,
                null=True,
                verbose_name="Código de Convenio Bancario (Recaudo Referenciado)",
            ),
        ),
        migrations.CreateModel(
            name="ReciboRecaudoBancario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "referencia",
                    models.CharField(
                        editable=False, max_length=25, verbose_name="Referencia de pago"
                    ),
                ),
                (
                    "monto_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Monto total"
                    ),
                ),
                ("fecha_limite", models.DateField(verbose_name="Fecha límite de pago")),
                ("año", models.PositiveIntegerField(verbose_name="Año")),
                ("mes", models.PositiveSmallIntegerField(verbose_name="Mes")),
                ("generado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "cuentas",
                    models.ManyToManyField(
                        related_name="recibos_recaudo_bancario",
                        to="finanzas.cuentaporcobrarestudiante",
                        verbose_name="Cuentas incluidas",
                    ),
                ),
                (
                    "estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recibos_recaudo_bancario",
                        to="gestion_academica.estudiante",
                        verbose_name="Estudiante",
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recibos_recaudo_bancario",
                        to="finanzas.institucioneducativa",
                        verbose_name="Institución",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recibo de Recaudo Bancario",
                "verbose_name_plural": "Recibos de Recaudo Bancario",
                "ordering": ["-año", "-mes"],
                "unique_together": {("estudiante", "año", "mes")},
            },
        ),
    ]
