# Generated by Django 5.2.17 on 2026-09-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0037_institucioneducativa_codigo_convenio_bancario_and_more"),
        ("simat", "0004_sede_principal_existentes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="institucioneducativa",
            name="aspirante",
        ),
        migrations.AddConstraint(
            model_name="institucioneducativa",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("codigo_convenio_bancario", ""), _negated=True),
                    ("codigo_convenio_bancario__isnull", False),
                ),
                fields=("codigo_convenio_bancario",),
                name="institucion_codigo_convenio_bancario_unico",
            ),
        ),
    ]
