# Generated by Django 5.2.17 on 2026-09-21 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0038_remove_institucioneducativa_aspirante_and_more"),
        ("gestion_academica", "0100_backfill_permisos_grupos_0039"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cuentaporcobrarestudiante",
            name="estudiante",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cuentas_por_cobrar",
                to="gestion_academica.estudiante",
            ),
        ),
        migrations.AlterField(
            model_name="pagoregistrado",
            name="cuenta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pagos",
                to="finanzas.cuentaporcobrarestudiante",
                verbose_name="Cuenta Asociada",
            ),
        ),
        migrations.AlterField(
            model_name="reciborecaudobancario",
            name="estudiante",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recibos_recaudo_bancario",
                to="gestion_academica.estudiante",
                verbose_name="Estudiante",
            ),
        ),
    ]
