# Generated by Django 5.2.17 on 2026-09-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0039_alter_cuentaporcobrarestudiante_estudiante_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cuentaporcobrarestudiante",
            name="ultimo_recordatorio_pago_enviado",
            field=models.DateField(
                blank=True,
                editable=False,
                help_text="Evita mandar el recordatorio dos veces el mismo día si el envío automático y el botón manual coinciden.",
                null=True,
                verbose_name="Fecha del último recordatorio de pago enviado",
            ),
        ),
    ]
