# Generated by Django 5.2.1 on 2026-05-15 21:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finanzas', '0011_ejecucionhealthcheck'),
        ('gestion_academica', '0024_asignar_permisos_portal_familiar_existentes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('ultimo_mensaje_en', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('archivada_por_a', models.BooleanField(default=False)),
                ('archivada_por_b', models.BooleanField(default=False)),
                ('estudiante_contexto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversaciones', to='gestion_academica.estudiante', verbose_name='Estudiante (contexto)')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones', to='finanzas.institucioneducativa', verbose_name='Institución')),
                ('participante_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_como_a', to=settings.AUTH_USER_MODEL, verbose_name='Docente / Coordinador')),
                ('participante_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_como_b', to=settings.AUTH_USER_MODEL, verbose_name='Familiar')),
            ],
            options={
                'verbose_name': 'Conversación',
                'verbose_name_plural': 'Conversaciones',
                'ordering': ['-ultimo_mensaje_en'],
                'permissions': [('puede_supervisar_mensajes', 'Puede ver todos los mensajes de la institución (coordinador/admin)')],
                'unique_together': {('participante_a', 'participante_b', 'estudiante_contexto')},
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=2000, verbose_name='Texto del mensaje')),
                ('adjunto', models.FileField(blank=True, null=True, upload_to='mensajeria/adjuntos/%Y/%m/', verbose_name='Archivo adjunto')),
                ('enviado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('leido', models.BooleanField(default=False, verbose_name='Leído')),
                ('leido_en', models.DateTimeField(blank=True, null=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='mensajeria.conversacion', verbose_name='Conversación')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Remitente')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['enviado_en'],
            },
        ),
    ]
