# Generated by Django 5.2.15 on 2026-06-17 19:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mensajeria", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mensaje",
            name="adjunto",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="mensajeria/adjuntos/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "pdf",
                            "doc",
                            "docx",
                            "ppt",
                            "pptx",
                            "xls",
                            "xlsx",
                            "txt",
                            "jpg",
                            "jpeg",
                            "png",
                            "gif",
                            "webp",
                        ]
                    )
                ],
                verbose_name="Archivo adjunto",
            ),
        ),
    ]
