# Generated by Django 5.2.15 on 2026-06-13 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("finanzas", "0015_add_bilingue_fields"),
        ("gestion_academica", "0038_dba_predefinido"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BancoPregunta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "es_publica",
                    models.BooleanField(
                        default=False,
                        help_text="Visible para todas las instituciones (preguntas de la plataforma)",
                        verbose_name="Pregunta pública",
                    ),
                ),
                (
                    "grado_nivel",
                    models.CharField(
                        choices=[
                            ("GRADO_3", "Saber 3°"),
                            ("GRADO_5", "Saber 5°"),
                            ("GRADO_7", "Saber 7°"),
                            ("GRADO_9", "Saber 9°"),
                            ("GRADO_11", "Saber 11°"),
                        ],
                        max_length=10,
                        verbose_name="Prueba / Grado",
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        choices=[
                            ("LECTURA_CRITICA", "Lectura Crítica"),
                            ("MATEMATICAS", "Matemáticas"),
                            ("CIENCIAS_NATURALES", "Ciencias Naturales"),
                            ("SOCIALES", "Ciencias Sociales y Ciudadanas"),
                            ("INGLES", "Inglés"),
                            ("LENGUAJE", "Lenguaje"),
                            ("FILOSOFIA", "Filosofía"),
                        ],
                        max_length=20,
                        verbose_name="Área",
                    ),
                ),
                (
                    "competencia",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Competencia"
                    ),
                ),
                (
                    "componente",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Componente"
                    ),
                ),
                ("enunciado", models.TextField(verbose_name="Enunciado")),
                (
                    "imagen_url",
                    models.URLField(blank=True, verbose_name="URL imagen (opcional)"),
                ),
                (
                    "nivel_dificultad",
                    models.CharField(
                        choices=[
                            ("BASICO", "Básico"),
                            ("MEDIO", "Medio"),
                            ("ALTO", "Alto"),
                        ],
                        default="MEDIO",
                        max_length=10,
                        verbose_name="Dificultad",
                    ),
                ),
                (
                    "explicacion",
                    models.TextField(
                        blank=True, verbose_name="Explicación de la respuesta"
                    ),
                ),
                (
                    "fuente",
                    models.CharField(
                        blank=True,
                        help_text="Ej: ICFES Saber 11 2019-1",
                        max_length=200,
                        verbose_name="Fuente",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="preguntas_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="banco_preguntas",
                        to="finanzas.institucioneducativa",
                        verbose_name="Institución",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pregunta del Banco",
                "verbose_name_plural": "Banco de Preguntas",
                "ordering": ["grado_nivel", "area", "pk"],
            },
        ),
        migrations.CreateModel(
            name="OpcionPregunta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "letra",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                        max_length=1,
                    ),
                ),
                ("texto", models.TextField(verbose_name="Texto")),
                ("es_correcta", models.BooleanField(default=False)),
                (
                    "pregunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opciones",
                        to="simulacros.bancopregunta",
                    ),
                ),
            ],
            options={
                "ordering": ["letra"],
                "unique_together": {("pregunta", "letra")},
            },
        ),
        migrations.CreateModel(
            name="PreguntaSimulacro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0)),
                (
                    "pregunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="simulacros.bancopregunta",
                    ),
                ),
            ],
            options={
                "ordering": ["orden"],
            },
        ),
        migrations.CreateModel(
            name="Simulacro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Instrucciones"),
                ),
                (
                    "grado_nivel",
                    models.CharField(
                        choices=[
                            ("GRADO_3", "Saber 3°"),
                            ("GRADO_5", "Saber 5°"),
                            ("GRADO_7", "Saber 7°"),
                            ("GRADO_9", "Saber 9°"),
                            ("GRADO_11", "Saber 11°"),
                        ],
                        max_length=10,
                        verbose_name="Dirigido a",
                    ),
                ),
                (
                    "tiempo_minutos",
                    models.PositiveIntegerField(
                        default=60, verbose_name="Tiempo (min)"
                    ),
                ),
                ("fecha_inicio", models.DateTimeField(verbose_name="Disponible desde")),
                ("fecha_cierre", models.DateTimeField(verbose_name="Cierra el")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("PUBLICADO", "Publicado"),
                            ("CERRADO", "Cerrado"),
                        ],
                        default="BORRADOR",
                        max_length=10,
                    ),
                ),
                (
                    "mostrar_respuestas",
                    models.BooleanField(
                        default=True, verbose_name="Mostrar respuestas al terminar"
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "docente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="simulacros_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simulacros",
                        to="finanzas.institucioneducativa",
                    ),
                ),
                (
                    "preguntas",
                    models.ManyToManyField(
                        blank=True,
                        through="simulacros.PreguntaSimulacro",
                        to="simulacros.bancopregunta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Simulacro",
                "verbose_name_plural": "Simulacros",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.AddField(
            model_name="preguntasimulacro",
            name="simulacro",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="simulacros.simulacro"
            ),
        ),
        migrations.CreateModel(
            name="IntentoSimulacro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inicio", models.DateTimeField(auto_now_add=True)),
                ("fin", models.DateTimeField(blank=True, null=True)),
                (
                    "puntaje",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Puntaje (%)"
                    ),
                ),
                ("completado", models.BooleanField(default=False)),
                (
                    "estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intentos_simulacro",
                        to="gestion_academica.estudiante",
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finanzas.institucioneducativa",
                    ),
                ),
                (
                    "simulacro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intentos",
                        to="simulacros.simulacro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Intento de Simulacro",
                "ordering": ["-inicio"],
                "unique_together": {("simulacro", "estudiante")},
            },
        ),
        migrations.CreateModel(
            name="RespuestaSimulacro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("es_correcta", models.BooleanField(default=False)),
                (
                    "intento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respuestas",
                        to="simulacros.intentosimulacro",
                    ),
                ),
                (
                    "opcion_elegida",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="simulacros.opcionpregunta",
                    ),
                ),
                (
                    "pregunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="simulacros.bancopregunta",
                    ),
                ),
            ],
            options={
                "unique_together": {("intento", "pregunta")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="preguntasimulacro",
            unique_together={("simulacro", "pregunta")},
        ),
    ]
