# Generated by Django 5.2.15 on 2026-06-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulacros", "0002_seed_banco_preguntas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bancopregunta",
            name="imagen_url",
            field=models.URLField(
                blank=True,
                help_text="Solo URLs http:// o https://",
                verbose_name="URL imagen (opcional)",
            ),
        ),
    ]
