# Generated by Django 5.2.1 on 2026-05-27 13:37

import django.db.models.deletion
import utils.encrypted_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finanzas', '0012_encrypt_credenciales_institucion'),
        ('gestion_academica', '0033_noticia_banner_revision'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionFactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=False, help_text='Habilita la facturación electrónica para esta institución. Lo activa el propietario de la plataforma tras el pago del adicional.', verbose_name='Módulo activo')),
                ('ambiente', models.CharField(choices=[('SANDBOX', 'Pruebas (Sandbox)'), ('PRODUCCION', 'Producción')], default='SANDBOX', max_length=12, verbose_name='Ambiente')),
                ('client_id', utils.encrypted_fields.EncryptedCharField(blank=True, null=True, verbose_name='Client ID (Factus)')),
                ('client_secret', utils.encrypted_fields.EncryptedCharField(blank=True, null=True, verbose_name='Client Secret (Factus)')),
                ('username', utils.encrypted_fields.EncryptedCharField(blank=True, null=True, verbose_name='Usuario / Email (Factus)')),
                ('password', utils.encrypted_fields.EncryptedCharField(blank=True, null=True, verbose_name='Contraseña (Factus)')),
                ('numbering_range_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID Rango de Numeración (DIAN)')),
                ('facturas_emitidas', models.PositiveIntegerField(default=0, verbose_name='Facturas emitidas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('institucion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_factus', to='finanzas.institucioneducativa', verbose_name='Institución')),
            ],
            options={
                'verbose_name': 'Configuración Factus',
                'verbose_name_plural': 'Configuraciones Factus',
            },
        ),
        migrations.CreateModel(
            name='FacturaElectronica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambiente', models.CharField(default='SANDBOX', max_length=12)),
                ('reference_code', models.CharField(help_text='Identificador idempotente enviado a Factus.', max_length=60, verbose_name='Código de referencia')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de envío'), ('VALIDADA', 'Validada por DIAN'), ('RECHAZADA', 'Rechazada por DIAN'), ('ERROR', 'Error de comunicación')], default='PENDIENTE', max_length=12)),
                ('numero', models.CharField(blank=True, max_length=60, verbose_name='Número DIAN')),
                ('cufe', models.CharField(blank=True, max_length=120, verbose_name='CUFE')),
                ('url_pdf', models.URLField(blank=True, verbose_name='URL del PDF')),
                ('url_xml', models.URLField(blank=True, verbose_name='URL del XML')),
                ('qr', models.TextField(blank=True, verbose_name='Contenido QR DIAN')),
                ('json_enviado', models.JSONField(blank=True, null=True)),
                ('json_respuesta', models.JSONField(blank=True, null=True)),
                ('mensaje', models.TextField(blank=True, verbose_name='Mensaje / Error')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_electronicas', to='gestion_academica.estudiante')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas_electronicas', to='finanzas.institucioneducativa')),
                ('pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_electronicas', to='finanzas.pagoregistrado')),
            ],
            options={
                'verbose_name': 'Factura Electrónica',
                'verbose_name_plural': 'Facturas Electrónicas',
                'ordering': ['-fecha_creacion'],
                'constraints': [models.UniqueConstraint(fields=('institucion', 'reference_code'), name='factura_electronica_ref_unica_por_institucion')],
            },
        ),
    ]
