# Generated by Django 5.2.1 on 2026-05-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_electronica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionfactus',
            name='emision_automatica',
            field=models.BooleanField(default=False, help_text='Si está activo, se emite la factura electrónica automáticamente al registrarse/confirmarse cada pago (efectivo o Mercado Pago). Si está apagado, la factura se emite manualmente con el botón.', verbose_name='Emisión automática'),
        ),
    ]
