# Generated by Django 5.2.1 on 2026-05-27 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_electronica', '0002_configuracionfactus_emision_automatica'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionfactus',
            name='numbering_range_id_nota_credito',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID Rango Numeración Nota Crédito (DIAN)'),
        ),
        migrations.AddField(
            model_name='configuracionfactus',
            name='numbering_range_id_nota_debito',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID Rango Numeración Nota Débito (DIAN)'),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='documento_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas', to='facturacion_electronica.facturaelectronica', verbose_name='Documento de origen'),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='tipo',
            field=models.CharField(choices=[('FACTURA', 'Factura de Venta'), ('NOTA_CREDITO', 'Nota Crédito'), ('NOTA_DEBITO', 'Nota Débito')], default='FACTURA', max_length=14, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='configuracionfactus',
            name='numbering_range_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID Rango Numeración Factura (DIAN)'),
        ),
    ]
