# Generated by Django 5.2.1 on 2026-05-28 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_electronica', '0003_configuracionfactus_numbering_range_id_nota_credito_and_more'),
        ('finanzas', '0013_pagoregistrado_anulado_pagoregistrado_anulado_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaelectronica',
            name='cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_electronicas', to='finanzas.cuentaporcobrarestudiante'),
        ),
    ]
