# Generated by Django 5.2.15 on 2026-06-25 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditoria", "0001_initial"),
        ("finanzas", "0021_add_castigo_auditoria"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroSesion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_evento",
                    models.CharField(
                        choices=[
                            ("LOGIN", "Inicio de sesión"),
                            ("LOGOUT", "Cierre de sesión"),
                            ("CIERRE_REMOTO", "Cierre remoto por administrador"),
                            (
                                "RESET_EMERGENCIA",
                                "Restablecimiento de contraseña (emergencia)",
                            ),
                        ],
                        default="LOGIN",
                        max_length=20,
                        verbose_name="Tipo de evento",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Dirección IP"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, default="", verbose_name="Dispositivo / navegador"
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=40,
                        verbose_name="Clave de sesión",
                    ),
                ),
                (
                    "fecha",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha"),
                ),
                (
                    "ejecutado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acciones_sesion_ejecutadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ejecutado por",
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="finanzas.institucioneducativa",
                        verbose_name="Institución",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registros_sesion",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Sesión",
                "verbose_name_plural": "Registros de Sesión",
                "ordering": ["-fecha"],
                "indexes": [
                    models.Index(
                        fields=["usuario", "fecha"], name="auditoria_s_usuario_idx"
                    ),
                    models.Index(
                        fields=["tipo_evento", "fecha"], name="auditoria_s_evento_idx"
                    ),
                    models.Index(
                        fields=["institucion", "fecha"], name="auditoria_s_institu_idx"
                    ),
                ],
            },
        ),
    ]
