# Generated by Django 5.2.15 on 2026-06-13 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("finanzas", "0015_add_bilingue_fields"),
        ("gestion_academica", "0038_dba_predefinido"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PIAR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "año_lectivo",
                    models.PositiveIntegerField(verbose_name="Año Lectivo"),
                ),
                (
                    "condicion",
                    models.CharField(
                        choices=[
                            ("COG", "Cognitiva"),
                            ("MOT", "Motriz"),
                            ("VIS", "Visual"),
                            ("AUD", "Auditiva"),
                            ("MUL", "Múltiple"),
                            ("APR", "Trastorno de Aprendizaje"),
                            ("CON", "Conductual-TDAH"),
                            ("TAL", "Talentos Excepcionales"),
                            ("OTR", "Otra"),
                        ],
                        max_length=3,
                        verbose_name="Condición",
                    ),
                ),
                (
                    "condicion_descripcion",
                    models.TextField(
                        blank=True, verbose_name="Descripción de la condición"
                    ),
                ),
                (
                    "fortalezas",
                    models.TextField(verbose_name="Fortalezas del estudiante"),
                ),
                (
                    "barreras",
                    models.TextField(verbose_name="Barreras para el aprendizaje"),
                ),
                ("apoyos", models.TextField(verbose_name="Apoyos requeridos")),
                (
                    "compromisos_familia",
                    models.TextField(
                        blank=True, verbose_name="Compromisos de la familia"
                    ),
                ),
                (
                    "compromisos_docentes",
                    models.TextField(
                        blank=True, verbose_name="Compromisos de los docentes"
                    ),
                ),
                (
                    "compromisos_institucion",
                    models.TextField(
                        blank=True, verbose_name="Compromisos de la institución"
                    ),
                ),
                (
                    "fecha_elaboracion",
                    models.DateField(verbose_name="Fecha de Elaboración"),
                ),
                (
                    "fecha_revision",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Revisión"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("ACTIVO", "Vigente"),
                            ("CERRADO", "Cerrado"),
                        ],
                        default="BORRADOR",
                        max_length=10,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "observaciones_generales",
                    models.TextField(
                        blank=True, verbose_name="Observaciones Generales"
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "docente_lider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="piars_liderados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Docente Líder",
                    ),
                ),
                (
                    "estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="piars",
                        to="gestion_academica.estudiante",
                        verbose_name="Estudiante",
                    ),
                ),
                (
                    "grado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="gestion_academica.grado",
                        verbose_name="Grado",
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="piars",
                        to="finanzas.institucioneducativa",
                        verbose_name="Institución",
                    ),
                ),
            ],
            options={
                "verbose_name": "PIAR",
                "verbose_name_plural": "PIARs",
                "ordering": ["-año_lectivo"],
                "unique_together": {("estudiante", "año_lectivo")},
            },
        ),
        migrations.CreateModel(
            name="AjustePIAR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "periodo",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Período 1"),
                            (2, "Período 2"),
                            (3, "Período 3"),
                            (4, "Período 4"),
                        ],
                        verbose_name="Período Académico",
                    ),
                ),
                ("logro_ajustado", models.TextField(verbose_name="Logro Ajustado")),
                (
                    "estrategias_flexibles",
                    models.TextField(verbose_name="Estrategias Flexibles"),
                ),
                (
                    "ajuste_evaluativo",
                    models.TextField(verbose_name="Ajuste Evaluativo"),
                ),
                (
                    "recursos_apoyo",
                    models.TextField(blank=True, verbose_name="Recursos de Apoyo"),
                ),
                (
                    "seguimiento",
                    models.TextField(blank=True, verbose_name="Seguimiento"),
                ),
                (
                    "alcanzado",
                    models.BooleanField(
                        default=False, verbose_name="¿Logro alcanzado?"
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="gestion_academica.materia",
                        verbose_name="Materia",
                    ),
                ),
                (
                    "piar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ajustes",
                        to="piar.piar",
                        verbose_name="PIAR",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ajuste PIAR",
                "verbose_name_plural": "Ajustes PIAR",
                "ordering": ["periodo", "materia__nombre_materia"],
            },
        ),
    ]
