# Generated by Django 5.2.1 on 2026-09-02 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("piar", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="piar",
            name="ultima_alerta_enviada",
            field=models.DateField(
                blank=True,
                help_text="Fecha del último aviso automático por ajustes no alcanzados (evita duplicados el mismo día).",
                null=True,
                verbose_name="Última alerta temprana enviada",
            ),
        ),
    ]
