# Generated by Django 5.2.17 on 2026-09-07 20:21

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("finanzas", "0036_seed_modulo_presupuesto"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Apropiacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor_inicial",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="Apropiación inicial",
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apropiaciones",
                        to="finanzas.institucioneducativa",
                        verbose_name="Institución",
                    ),
                ),
            ],
            options={
                "verbose_name": "Apropiación Presupuestal",
                "verbose_name_plural": "Apropiaciones Presupuestales",
            },
        ),
        migrations.CreateModel(
            name="CDP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.PositiveIntegerField(editable=False, verbose_name="Número"),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Valor"
                    ),
                ),
                (
                    "objeto",
                    models.CharField(
                        help_text="Para qué se aparta este dinero.",
                        max_length=255,
                        verbose_name="Objeto",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("VIGENTE", "Vigente"),
                            ("ANULADO", "Anulado"),
                            ("AGOTADO", "Agotado"),
                        ],
                        default="VIGENTE",
                        max_length=10,
                    ),
                ),
                (
                    "fecha_expedicion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de expedición"
                    ),
                ),
                (
                    "anulado_motivo",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Motivo de anulación"
                    ),
                ),
                (
                    "apropiacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cdps",
                        to="presupuesto.apropiacion",
                        verbose_name="Apropiación",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cdps",
                        to="finanzas.institucioneducativa",
                        verbose_name="Institución",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificado de Disponibilidad Presupuestal (CDP)",
                "verbose_name_plural": "Certificados de Disponibilidad Presupuestal (CDP)",
                "ordering": ["-numero"],
            },
        ),
        migrations.CreateModel(
            name="ModificacionPresupuestal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ADICION", "Adición"),
                            ("REDUCCION", "Reducción"),
                            ("TRASLADO", "Traslado"),
                        ],
                        max_length=12,
                        verbose_name="Tipo de movimiento",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Valor"
                    ),
                ),
                (
                    "acto_administrativo",
                    models.CharField(
                        blank=True,
                        help_text="Ej: Resolución 014 del 12/03/2026 del Consejo Directivo.",
                        max_length=255,
                        verbose_name="Acto administrativo",
                    ),
                ),
                (
                    "soporte",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="presupuesto/modificaciones/",
                        verbose_name="Soporte (PDF)",
                    ),
                ),
                (
                    "fecha",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de registro"
                    ),
                ),
                (
                    "apropiacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modificaciones",
                        to="presupuesto.apropiacion",
                        verbose_name="Apropiación (origen)",
                    ),
                ),
                (
                    "apropiacion_destino",
                    models.ForeignKey(
                        blank=True,
                        help_text="Obligatorio solo para movimientos de tipo Traslado: el rubro que RECIBE el valor.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="traslados_recibidos",
                        to="presupuesto.apropiacion",
                        verbose_name="Apropiación destino (solo traslados)",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modificaciones_presupuestales",
                        to="finanzas.institucioneducativa",
                        verbose_name="Institución",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modificación Presupuestal",
                "verbose_name_plural": "Modificaciones Presupuestales",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="RP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.PositiveIntegerField(editable=False, verbose_name="Número"),
                ),
                (
                    "objeto_contrato",
                    models.CharField(
                        max_length=255, verbose_name="Objeto del contrato"
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Valor"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("VIGENTE", "Vigente"),
                            ("ANULADO", "Anulado"),
                            ("LIQUIDADO", "Liquidado"),
                        ],
                        default="VIGENTE",
                        max_length=10,
                    ),
                ),
                (
                    "fecha",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de registro"
                    ),
                ),
                (
                    "anulado_motivo",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Motivo de anulación"
                    ),
                ),
                (
                    "cdp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registros_presupuestales",
                        to="presupuesto.cdp",
                        verbose_name="CDP",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros_presupuestales",
                        to="finanzas.institucioneducativa",
                        verbose_name="Institución",
                    ),
                ),
                (
                    "tercero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registros_presupuestales",
                        to="finanzas.proveedor",
                        verbose_name="Tercero / contratista",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro Presupuestal (RP)",
                "verbose_name_plural": "Registros Presupuestales (RP)",
                "ordering": ["-numero"],
                "unique_together": {("institucion", "numero")},
            },
        ),
        migrations.CreateModel(
            name="Obligacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.PositiveIntegerField(editable=False, verbose_name="Número"),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Valor"
                    ),
                ),
                (
                    "soporte_recibido_satisfaccion",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="presupuesto/obligaciones/",
                        verbose_name="Soporte (acta / factura)",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("VIGENTE", "Vigente"),
                            ("ANULADA", "Anulada"),
                            ("PAGADA", "Pagada"),
                        ],
                        default="VIGENTE",
                        max_length=10,
                    ),
                ),
                (
                    "fecha",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de registro"
                    ),
                ),
                (
                    "anulado_motivo",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Motivo de anulación"
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="obligaciones",
                        to="finanzas.institucioneducativa",
                        verbose_name="Institución",
                    ),
                ),
                (
                    "rp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="obligaciones",
                        to="presupuesto.rp",
                        verbose_name="Registro Presupuestal (RP)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Obligación",
                "verbose_name_plural": "Obligaciones",
                "ordering": ["-numero"],
                "unique_together": {("institucion", "numero")},
            },
        ),
        migrations.CreateModel(
            name="RubroPresupuestalGasto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=20, verbose_name="Código")),
                ("nombre", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("FUNCIONAMIENTO", "Funcionamiento"),
                            ("INVERSION", "Inversión"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de gasto",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rubros_gasto",
                        to="finanzas.institucioneducativa",
                        verbose_name="Institución",
                    ),
                ),
                (
                    "rubro_padre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hijos",
                        to="presupuesto.rubropresupuestalgasto",
                        verbose_name="Rubro padre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rubro Presupuestal de Gasto",
                "verbose_name_plural": "Rubros Presupuestales de Gasto",
                "ordering": ["codigo"],
                "unique_together": {("institucion", "codigo")},
            },
        ),
        migrations.AddField(
            model_name="apropiacion",
            name="rubro",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="apropiaciones",
                to="presupuesto.rubropresupuestalgasto",
                verbose_name="Rubro de gasto",
            ),
        ),
        migrations.CreateModel(
            name="RubroPresupuestalIngreso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=20, verbose_name="Código")),
                ("nombre", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "tipo_recurso",
                    models.CharField(
                        choices=[
                            ("SGP", "Sistema General de Participaciones"),
                            ("RECURSOS_PROPIOS", "Recursos propios"),
                            ("TRANSFERENCIAS", "Transferencias territoriales"),
                            ("RECURSOS_CAPITAL", "Recursos de capital"),
                            ("DONACIONES", "Donaciones"),
                        ],
                        max_length=20,
                        verbose_name="Fuente de financiación",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rubros_ingreso",
                        to="finanzas.institucioneducativa",
                        verbose_name="Institución",
                    ),
                ),
                (
                    "rubro_padre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hijos",
                        to="presupuesto.rubropresupuestalingreso",
                        verbose_name="Rubro padre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rubro Presupuestal de Ingreso",
                "verbose_name_plural": "Rubros Presupuestales de Ingreso",
                "ordering": ["codigo"],
                "unique_together": {("institucion", "codigo")},
            },
        ),
        migrations.CreateModel(
            name="VigenciaFiscal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anio", models.PositiveIntegerField(verbose_name="Año")),
                (
                    "estado",
                    models.CharField(
                        choices=[("ABIERTA", "Abierta"), ("CERRADA", "Cerrada")],
                        default="ABIERTA",
                        max_length=10,
                    ),
                ),
                (
                    "fecha_apertura",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de apertura"
                    ),
                ),
                (
                    "fecha_cierre",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de cierre"
                    ),
                ),
                (
                    "cerrada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cerrada por",
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vigencias_fiscales",
                        to="finanzas.institucioneducativa",
                        verbose_name="Institución",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vigencia Fiscal",
                "verbose_name_plural": "Vigencias Fiscales",
                "ordering": ["-anio"],
                "unique_together": {("institucion", "anio")},
            },
        ),
        migrations.AddField(
            model_name="cdp",
            name="vigencia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cdps",
                to="presupuesto.vigenciafiscal",
                verbose_name="Vigencia fiscal",
            ),
        ),
        migrations.AddField(
            model_name="apropiacion",
            name="vigencia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="apropiaciones",
                to="presupuesto.vigenciafiscal",
                verbose_name="Vigencia fiscal",
            ),
        ),
        migrations.CreateModel(
            name="OrdenDePago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.PositiveIntegerField(editable=False, verbose_name="Número"),
                ),
                (
                    "valor_bruto",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Valor bruto"
                    ),
                ),
                (
                    "total_retenciones",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="Total retenciones",
                    ),
                ),
                (
                    "valor_neto",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        verbose_name="Valor neto a pagar",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("GENERADA", "Generada"),
                            ("PAGADA", "Pagada"),
                            ("ANULADA", "Anulada"),
                        ],
                        default="GENERADA",
                        max_length=10,
                    ),
                ),
                (
                    "fecha",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de registro"
                    ),
                ),
                (
                    "anulado_motivo",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Motivo de anulación"
                    ),
                ),
                (
                    "beneficiario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordenes_de_pago",
                        to="finanzas.proveedor",
                        verbose_name="Beneficiario",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ordenes_de_pago",
                        to="finanzas.institucioneducativa",
                        verbose_name="Institución",
                    ),
                ),
                (
                    "obligacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordenes_de_pago",
                        to="presupuesto.obligacion",
                        verbose_name="Obligación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Orden de Pago",
                "verbose_name_plural": "Órdenes de Pago",
                "ordering": ["-numero"],
                "unique_together": {("institucion", "numero")},
            },
        ),
        migrations.CreateModel(
            name="PresupuestoIngreso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor_inicial",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="Valor presupuestado",
                    ),
                ),
                (
                    "valor_recaudado",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="Valor recaudado",
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presupuestos_ingreso",
                        to="finanzas.institucioneducativa",
                        verbose_name="Institución",
                    ),
                ),
                (
                    "rubro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="presupuestos",
                        to="presupuesto.rubropresupuestalingreso",
                        verbose_name="Rubro de ingreso",
                    ),
                ),
                (
                    "vigencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presupuestos_ingreso",
                        to="presupuesto.vigenciafiscal",
                        verbose_name="Vigencia fiscal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Presupuesto de Ingreso",
                "verbose_name_plural": "Presupuestos de Ingreso",
                "unique_together": {("vigencia", "rubro")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="cdp",
            unique_together={("institucion", "vigencia", "numero")},
        ),
        migrations.AlterUniqueTogether(
            name="apropiacion",
            unique_together={("vigencia", "rubro")},
        ),
    ]
