# Generated by Django 5.2.17 on 2026-09-07 21:02

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0036_seed_modulo_presupuesto"),
        ("presupuesto", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogoGeneralCuentas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=20, unique=True, verbose_name="Código"),
                ),
                ("nombre", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "naturaleza",
                    models.CharField(
                        choices=[("DEBITO", "Débito"), ("CREDITO", "Crédito")],
                        max_length=10,
                    ),
                ),
                (
                    "permite_movimientos",
                    models.BooleanField(
                        default=True,
                        help_text='Si está desactivado, es una cuenta "de agrupación" (ej. una clase o grupo) que no recibe movimientos directos, solo sus subcuentas.',
                        verbose_name="Permite movimientos",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activa")),
                (
                    "cuenta_padre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hijas",
                        to="presupuesto.catalogogeneralcuentas",
                        verbose_name="Cuenta padre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cuenta del Catálogo General de Cuentas",
                "verbose_name_plural": "Catálogo General de Cuentas (CGC)",
                "ordering": ["codigo"],
            },
        ),
        migrations.AddField(
            model_name="rubropresupuestalgasto",
            name="cuenta_cgc_gasto",
            field=models.ForeignKey(
                blank=True,
                help_text="La cuenta que se debita al causar contablemente un pago de este rubro. Sin esto, no se puede generar el comprobante contable.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rubros_gasto",
                to="presupuesto.catalogogeneralcuentas",
                verbose_name="Cuenta contable (CGC) de este gasto",
            ),
        ),
        migrations.CreateModel(
            name="ComprobanteContable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.PositiveIntegerField(editable=False, verbose_name="Número"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("EGRESO", "Comprobante de Egreso"),
                            ("AJUSTE", "Ajuste / Reversión"),
                        ],
                        default="EGRESO",
                        max_length=10,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("CONTABILIZADO", "Contabilizado"),
                            ("ANULADO", "Anulado"),
                        ],
                        default="BORRADOR",
                        max_length=15,
                    ),
                ),
                (
                    "fecha",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "fecha_contabilizacion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de contabilización"
                    ),
                ),
                (
                    "anulado_motivo",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Motivo de anulación"
                    ),
                ),
                (
                    "comprobante_que_reversa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversiones",
                        to="presupuesto.comprobantecontable",
                        verbose_name="Comprobante que reversa (solo ajustes)",
                    ),
                ),
                (
                    "contabilizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comprobantes_contables",
                        to="finanzas.institucioneducativa",
                        verbose_name="Institución",
                    ),
                ),
                (
                    "orden_pago",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comprobante_contable",
                        to="presupuesto.ordendepago",
                        verbose_name="Orden de Pago de origen",
                    ),
                ),
                (
                    "vigencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comprobantes_contables",
                        to="presupuesto.vigenciafiscal",
                        verbose_name="Vigencia fiscal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comprobante Contable",
                "verbose_name_plural": "Comprobantes Contables",
                "ordering": ["-numero"],
                "unique_together": {("institucion", "numero")},
            },
        ),
        migrations.CreateModel(
            name="ConceptoRetencion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("RETEFUENTE", "Retención en la Fuente"),
                            ("RETEICA", "ReteICA"),
                            ("ESTAMPILLA", "Estampilla territorial"),
                            ("OTRA", "Otra retención"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text='Ej: "Estampilla Pro-Cultura", "ReteFuente servicios".',
                        max_length=150,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "tarifa_porcentaje",
                    models.DecimalField(
                        decimal_places=3, max_digits=6, verbose_name="Tarifa (%)"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "cuenta_puc_pasivo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conceptos_retencion",
                        to="presupuesto.catalogogeneralcuentas",
                        verbose_name="Cuenta PUC del pasivo (por pagar)",
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conceptos_retencion",
                        to="finanzas.institucioneducativa",
                        verbose_name="Institución",
                    ),
                ),
            ],
            options={
                "verbose_name": "Concepto de Retención",
                "verbose_name_plural": "Conceptos de Retención",
                "ordering": ["tipo", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="MovimientoContable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Descripción"
                    ),
                ),
                (
                    "valor_debito",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="Débito",
                    ),
                ),
                (
                    "valor_credito",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="Crédito",
                    ),
                ),
                (
                    "comprobante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos",
                        to="presupuesto.comprobantecontable",
                        verbose_name="Comprobante",
                    ),
                ),
                (
                    "cuenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos",
                        to="presupuesto.catalogogeneralcuentas",
                        verbose_name="Cuenta (CGC)",
                    ),
                ),
                (
                    "tercero",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos_contables",
                        to="finanzas.proveedor",
                        verbose_name="Tercero",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento Contable",
                "verbose_name_plural": "Movimientos Contables",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="RetencionAplicada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_gravable",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Base gravable"
                    ),
                ),
                (
                    "tarifa_porcentaje",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=6,
                        verbose_name="Tarifa aplicada (%)",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Valor retenido"
                    ),
                ),
                (
                    "concepto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retenciones_aplicadas",
                        to="presupuesto.conceptoretencion",
                        verbose_name="Concepto",
                    ),
                ),
                (
                    "orden_pago",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retenciones",
                        to="presupuesto.ordendepago",
                        verbose_name="Orden de Pago",
                    ),
                ),
            ],
            options={
                "verbose_name": "Retención Aplicada",
                "verbose_name_plural": "Retenciones Aplicadas",
                "ordering": ["id"],
            },
        ),
    ]
