# Generated by Django 5.2.17 on 2026-09-07 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("presupuesto", "0003_seed_catalogo_cgc_base"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaCPC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        max_length=15, unique=True, verbose_name="Código CPC"
                    ),
                ),
                ("titulo", models.CharField(max_length=255, verbose_name="Título")),
                (
                    "tipo",
                    models.CharField(
                        choices=[("BIEN", "Bien"), ("SERVICIO", "Servicio")],
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoría CPC",
                "verbose_name_plural": "Categorías CPC (Bienes y Servicios)",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="FuenteFinanciacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ambito_codigo", models.PositiveSmallIntegerField()),
                ("ambito_nombre", models.CharField(max_length=100)),
                ("grupo_codigo", models.PositiveSmallIntegerField()),
                ("grupo_nombre", models.CharField(max_length=200)),
                ("subgrupo_codigo", models.PositiveSmallIntegerField()),
                ("subgrupo_nombre", models.CharField(max_length=200)),
                ("clase_codigo", models.PositiveSmallIntegerField()),
                ("clase_nombre", models.CharField(max_length=200)),
                ("subclase_codigo", models.CharField(max_length=10)),
                ("subclase_nombre", models.CharField(max_length=200)),
                (
                    "codigo_fuente",
                    models.CharField(max_length=20, unique=True, verbose_name="Código"),
                ),
                (
                    "nombre_cuenta",
                    models.CharField(max_length=255, verbose_name="Nombre completo"),
                ),
                (
                    "aplica_establecimientos_publicos_territoriales",
                    models.BooleanField(
                        default=False,
                        help_text="Aplica a establecimientos públicos como un Fondo de Servicios Educativos.",
                    ),
                ),
                ("aplica_departamentos", models.BooleanField(default=False)),
                ("aplica_municipios", models.BooleanField(default=False)),
                ("aplica_bogota", models.BooleanField(default=False)),
                ("aplica_san_andres", models.BooleanField(default=False)),
                (
                    "aplica_empresas_territoriales_no_financieras",
                    models.BooleanField(default=False),
                ),
                (
                    "aplica_empresas_nacionales_no_financieras",
                    models.BooleanField(default=False),
                ),
            ],
            options={
                "verbose_name": "Fuente de Financiación",
                "verbose_name_plural": "Fuentes de Financiación (CHIP)",
                "ordering": ["codigo_fuente"],
            },
        ),
        migrations.AddField(
            model_name="rp",
            name="categoria_cpc",
            field=models.ForeignKey(
                blank=True,
                help_text="Qué bien o servicio se está comprando, según el catálogo CPC del DANE.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="registros_presupuestales",
                to="presupuesto.categoriacpc",
                verbose_name="Clasificación CPC (bien/servicio)",
            ),
        ),
        # No se usa AlterField: el campo pasa de CharField (con choices libres
        # SGP/RECURSOS_PROPIOS/...) a ForeignKey al catálogo oficial CHIP, y
        # esos valores de texto no tienen un equivalente automático fiable en
        # el catálogo de 230 fuentes (los nombres no coinciden literalmente;
        # ver conversación de diseño). Se separa en Remove+Add para que la
        # migración nunca intente convertir el texto viejo a un ID numérico
        # (eso rompería el ALTER en Postgres si ya existiera algún rubro
        # cargado). Si ya hay rubros creados, quedan con la fuente en blanco
        # y el contador la reasigna manualmente al editarlos — no se inventa
        # un mapeo automático de un campo contable/legal sin su revisión.
        migrations.RemoveField(
            model_name="rubropresupuestalingreso",
            name="tipo_recurso",
        ),
        migrations.AddField(
            model_name="rubropresupuestalingreso",
            name="tipo_recurso",
            field=models.ForeignKey(
                blank=True,
                help_text="Catálogo oficial CHIP de la Contaduría General de la Nación. Nulo solo en rubros creados antes de este catálogo — reasígnalo al editar.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rubros_ingreso",
                to="presupuesto.fuentefinanciacion",
                verbose_name="Fuente de financiación (CHIP)",
            ),
        ),
    ]
