# Generated by Django 5.2.17 on 2026-09-07 23:19

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0036_seed_modulo_presupuesto"),
        ("presupuesto", "0006_seed_categoria_cpc"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CuentaBancaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("banco", models.CharField(max_length=100, verbose_name="Banco")),
                (
                    "numero_cuenta",
                    models.CharField(max_length=30, verbose_name="Número de cuenta"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("AHORROS", "Cuenta de Ahorros"),
                            ("CORRIENTE", "Cuenta Corriente"),
                        ],
                        default="AHORROS",
                        max_length=10,
                    ),
                ),
                (
                    "saldo_inicial",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="Saldo inicial",
                    ),
                ),
                ("activa", models.BooleanField(default=True, verbose_name="Activa")),
                (
                    "cuenta_cgc",
                    models.ForeignKey(
                        help_text="La cuenta del catálogo (ej. 1110 Bancos) que se acredita al pagar desde esta cuenta.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cuentas_bancarias",
                        to="presupuesto.catalogogeneralcuentas",
                        verbose_name="Cuenta contable (CGC) de bancos",
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cuentas_bancarias",
                        to="finanzas.institucioneducativa",
                        verbose_name="Institución",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cuenta Bancaria",
                "verbose_name_plural": "Cuentas Bancarias",
                "ordering": ["banco", "numero_cuenta"],
                "unique_together": {("institucion", "banco", "numero_cuenta")},
            },
        ),
        migrations.AddField(
            model_name="comprobantecontable",
            name="cuenta_bancaria",
            field=models.ForeignKey(
                blank=True,
                help_text="De dónde sale la plata. Se usa para mover el saldo real en Tesorería al contabilizar.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="comprobantes",
                to="presupuesto.cuentabancaria",
                verbose_name="Cuenta bancaria de pago",
            ),
        ),
        migrations.CreateModel(
            name="ElementoAlmacen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=30, verbose_name="Código")),
                ("nombre", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "unidad_medida",
                    models.CharField(
                        default="Unidad", max_length=30, verbose_name="Unidad de medida"
                    ),
                ),
                (
                    "stock_minimo",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Stock mínimo (alerta)"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elementos_almacen",
                        to="finanzas.institucioneducativa",
                        verbose_name="Institución",
                    ),
                ),
            ],
            options={
                "verbose_name": "Elemento de Almacén",
                "verbose_name_plural": "Elementos de Almacén",
                "ordering": ["codigo"],
                "unique_together": {("institucion", "codigo")},
            },
        ),
        migrations.CreateModel(
            name="MovimientoAlmacen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("ENTRADA", "Entrada"), ("SALIDA", "Salida")],
                        max_length=10,
                    ),
                ),
                ("cantidad", models.PositiveIntegerField(verbose_name="Cantidad")),
                (
                    "valor_unitario",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="Valor unitario",
                    ),
                ),
                (
                    "responsable",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Entregado a / recibido de",
                    ),
                ),
                (
                    "fecha",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha"),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "elemento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos",
                        to="presupuesto.elementoalmacen",
                        verbose_name="Elemento",
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos_almacen",
                        to="finanzas.institucioneducativa",
                        verbose_name="Institución",
                    ),
                ),
                (
                    "rp",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movimientos_almacen",
                        to="presupuesto.rp",
                        verbose_name="RP de origen (compra)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de Almacén",
                "verbose_name_plural": "Movimientos de Almacén",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="MovimientoTesoreria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("INGRESO", "Ingreso"), ("EGRESO", "Egreso")],
                        max_length=10,
                    ),
                ),
                ("concepto", models.CharField(max_length=255, verbose_name="Concepto")),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Valor"
                    ),
                ),
                (
                    "fecha",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha"),
                ),
                (
                    "conciliado",
                    models.BooleanField(default=False, verbose_name="Conciliado"),
                ),
                (
                    "fecha_conciliacion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de conciliación"
                    ),
                ),
                (
                    "comprobante_contable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos_tesoreria",
                        to="presupuesto.comprobantecontable",
                        verbose_name="Comprobante contable de origen",
                    ),
                ),
                (
                    "cuenta_bancaria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos",
                        to="presupuesto.cuentabancaria",
                        verbose_name="Cuenta bancaria",
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos_tesoreria",
                        to="finanzas.institucioneducativa",
                        verbose_name="Institución",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de Tesorería",
                "verbose_name_plural": "Movimientos de Tesorería",
                "ordering": ["-fecha"],
            },
        ),
    ]
