# Generated by Django 5.2.17 on 2026-09-08 16:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "presupuesto",
            "0007_cuentabancaria_comprobantecontable_cuenta_bancaria_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="modificacionpresupuestal",
            name="soporte",
            field=models.FileField(
                blank=True,
                help_text="Sube el acto administrativo (ej. resolución del Consejo Directivo) en PDF, o una foto/escaneo en JPG o PNG si no tienes el PDF.",
                null=True,
                upload_to="presupuesto/modificaciones/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                    )
                ],
                verbose_name="Soporte (PDF, JPG o PNG)",
            ),
        ),
    ]
