# Generated by Django 5.2.15 on 2026-06-17 19:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elearning", "0003_inscripcioncurso_cuenta_por_cobrar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curso",
            name="imagen_portada",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="elearning/portadas/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp", "gif"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="archivo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="elearning/materiales/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "pdf",
                            "doc",
                            "docx",
                            "ppt",
                            "pptx",
                            "xls",
                            "xlsx",
                            "txt",
                            "jpg",
                            "jpeg",
                            "png",
                            "gif",
                            "mp4",
                            "mp3",
                            "zip",
                        ]
                    )
                ],
            ),
        ),
    ]
