# Generated by Django 5.2.1 on 2025-07-20 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('tiempo_limite', models.PositiveIntegerField(default=30, help_text='Duración en minutos (0 para ilimitado)')),
                ('intentos_permitidos', models.PositiveIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
                ('mostrar_respuestas', models.BooleanField(default=False, help_text='Mostrar respuestas correctas al finalizar')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cuestionario',
                'verbose_name_plural': 'Cuestionarios',
                'ordering': ['-fecha_creacion'],
                'permissions': [('can_toggle_active', 'Puede activar/desactivar cuestionarios')],
            },
        ),
        migrations.CreateModel(
            name='OpcionPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500)),
                ('es_correcta', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Opción',
                'verbose_name_plural': 'Opciones',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='PreguntaCuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('tipo', models.CharField(choices=[('opcion_multiple', 'Opción Múltiple'), ('verdadero_falso', 'Verdadero/Falso'), ('texto_libre', 'Texto Libre'), ('emparejamiento', 'Emparejamiento')], default='opcion_multiple', max_length=20)),
                ('puntaje', models.PositiveIntegerField(default=1)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('retroalimentacion', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'ordering': ['orden'],
            },
        ),
    ]
