# Generated by Django 5.2.1 on 2025-07-20 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuestionarios', '0001_initial'),
        ('finanzas', '0001_initial'),
        ('gestion_academica', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cuestionario',
            name='actividad_calificable',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuestionario', to='gestion_academica.actividadcalificable'),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzas.institucioneducativa'),
        ),
        migrations.AddField(
            model_name='preguntacuestionario',
            name='cuestionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='cuestionarios.cuestionario'),
        ),
        migrations.AddField(
            model_name='opcionpregunta',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='cuestionarios.preguntacuestionario'),
        ),
        migrations.AlterUniqueTogether(
            name='preguntacuestionario',
            unique_together={('cuestionario', 'orden')},
        ),
    ]
