# Generated by Django 5.2.1 on 2025-08-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionarios', '0003_alter_preguntacuestionario_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcionpregunta',
            name='respuesta',
            field=models.CharField(blank=True, help_text='Solo para preguntas de emparejamiento: la respuesta con la que se debe emparejar este texto.', max_length=500, null=True),
        ),
    ]
