# Generated by Django 5.2.1 on 2025-08-01 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionarios', '0004_opcionpregunta_respuesta'),
        ('finanzas', '0003_cuentacontable_institucion_and_more'),
        ('gestion_academica', '0016_alter_bloquehorario_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntentoCuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('puntaje_obtenido', models.FloatField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('EN_PROGRESO', 'En Progreso'), ('FINALIZADO', 'Finalizado')], default='EN_PROGRESO', max_length=20)),
                ('cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='cuestionarios.cuestionario')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos_cuestionarios', to='gestion_academica.estudiante')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzas.institucioneducativa')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_respuesta', models.TextField(blank=True, null=True)),
                ('intento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='cuestionarios.intentocuestionario')),
                ('opciones_seleccionadas', models.ManyToManyField(blank=True, to='cuestionarios.opcionpregunta')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.preguntacuestionario')),
            ],
        ),
    ]
