# Generated by Django 5.2.1 on 2025-08-01 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionarios', '0005_intentocuestionario_respuestaestudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcionpregunta',
            name='emparejamiento',
            field=models.CharField(blank=True, help_text='Para Emparejamiento, este es el segundo elemento del par.', max_length=500, null=True),
        ),
    ]
