# Generated by Django 5.2.1 on 2025-08-02 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionarios', '0006_opcionpregunta_emparejamiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opcionpregunta',
            name='respuesta',
        ),
        migrations.AlterField(
            model_name='opcionpregunta',
            name='emparejamiento',
            field=models.CharField(blank=True, help_text='Solo para preguntas de emparejamiento: la respuesta con la que se debe emparejar este texto.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='opcionpregunta',
            name='texto',
            field=models.CharField(help_text='Para Emparejamiento, este es el primer elemento del par.', max_length=500),
        ),
    ]
