# Generated by Django 5.2.1 on 2025-08-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionarios', '0007_remove_opcionpregunta_respuesta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestaestudiante',
            name='puntaje_obtenido',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='respuestaestudiante',
            name='respuesta_emparejamiento',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
