# Generated by Django 5.2.1 on 2025-08-02 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionarios', '0008_respuestaestudiante_puntaje_obtenido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intentocuestionario',
            name='intento_extra_habilitado',
            field=models.BooleanField(default=False, help_text='Si se marca, permite al estudiante realizar un intento adicional.'),
        ),
    ]
