# Generated by Django 5.2.1 on 2025-08-03 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionarios', '0009_intentocuestionario_intento_extra_habilitado'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntacuestionario',
            name='respuesta_correcta_abierta',
            field=models.TextField(blank=True, help_text='Para preguntas de texto libre, describe aquí la respuesta ideal o los puntos clave que el estudiante debe mencionar.', null=True, verbose_name='Rúbrica o Respuesta Correcta (para preguntas abiertas)'),
        ),
    ]
