# Generated by Django 5.2.1 on 2026-08-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuestionarios", "0020_pregunta_accesibilidad_ia"),
    ]

    operations = [
        migrations.AddField(
            model_name="preguntacuestionario",
            name="audio",
            field=models.FileField(
                blank=True,
                help_text="Opcional: enunciado o explicación en voz. Se puede transcribir con IA.",
                null=True,
                upload_to="cuestionarios/preguntas/audio/%Y/%m/",
                verbose_name="Audio de apoyo de la pregunta",
            ),
        ),
        migrations.AddField(
            model_name="preguntacuestionario",
            name="audio_transcripcion",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Subtítulo del audio para estudiantes sordos o con dificultad auditiva.",
                verbose_name="Transcripción del audio (IA)",
            ),
        ),
    ]
