# Generated by Django 5.2.1 on 2026-08-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuestionarios", "0021_pregunta_audio"),
    ]

    operations = [
        migrations.AddField(
            model_name="preguntacuestionario",
            name="imagen_descripcion",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Descripción detallada del gráfico/imagen para estudiantes que no la ven; se puede escuchar con lectura por voz.",
                verbose_name="Audio-descripción de la imagen (IA)",
            ),
        ),
    ]
