# Generated by Django 5.2.1 on 2026-02-28 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finanzas', '0003_cuentacontable_institucion_and_more'),
        ('gestion_academica', '0021_alter_periodoacademico_año_escolar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('imagen_portada', models.ImageField(blank=True, null=True, upload_to='cursos/portadas/')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('duracion_horas', models.PositiveIntegerField(default=0, help_text='Duración en horas para el certificado')),
                ('publicado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('concepto_pago_asociado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.conceptopago')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_virtuales', to='finanzas.institucioneducativa')),
            ],
        ),
        migrations.CreateModel(
            name='InscripcionCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('progreso_porcentaje', models.FloatField(default=0.0)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_inscritos', to='gestion_academica.estudiante')),
            ],
            options={
                'unique_together': {('estudiante', 'curso')},
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='cursos.curso')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('PDF', 'Documento PDF'), ('VIDEO', 'Video YouTube'), ('ENLACE', 'Enlace Externo')], max_length=10)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='cursos/materiales/')),
                ('enlace', models.URLField(blank=True, help_text='URL del video de YouTube o enlace externo', null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='cursos.modulo')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('porcentaje_aprobacion', models.PositiveIntegerField(default=60, help_text='Puntaje mínimo de 0 a 100 para aprobar')),
                ('intentos_permitidos', models.PositiveIntegerField(default=3, help_text='0 para ilimitados')),
                ('modulo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion', to='cursos.modulo')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('puntos', models.PositiveIntegerField(default=10)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='cursos.evaluacion')),
            ],
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('es_correcta', models.BooleanField(default=False)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='cursos.pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='ProgresoModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completado', models.BooleanField(default=False)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('aprobado', models.BooleanField(default=False)),
                ('intentos_usados', models.PositiveIntegerField(default=0)),
                ('mejor_nota', models.FloatField(default=0.0)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos_modulos', to='cursos.inscripcioncurso')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.modulo')),
            ],
            options={
                'unique_together': {('inscripcion', 'modulo')},
            },
        ),
    ]
