import os
from django.contrib.auth import get_user_model
from django.shortcuts import redirect
"""
Django settings for proyecto_colegio project.

NOTA: Este archivo no es el módulo de settings activo del proyecto HALU.
Usa `proyecto_colegio.settings` (un nivel arriba, junto a este paquete).

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

def verificar_registro_inicial(get_response):
    def middleware(request):
        if not get_user_model().objects.exists() and not request.path.startswith('/registro_inicial'):
            return redirect('registro_inicial')
        return get_response(request)
    return middleware

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^+db=_7=t5h&i31zmskvzq3c=784^o7lji((!vqcyo^3&#ayx7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'crispy_bootstrap5',
    'gestion_academica.apps.GestionAcademicaConfig', # O 'gestion_academica' si no has personalizado apps.py
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware', # LocaleMiddleware va después de SessionMiddleware
    'django.middleware.locale.LocaleMiddleware',          # <--- ASEGÚRATE DE QUE ESTÉ AQUÍ
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'proyecto_colegio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')], # Para plantillas a nivel de proyecto (ej: registration/login.html)
        'APP_DIRS': True, # Para que Django busque plantillas dentro de las carpetas 'templates' de cada app
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request', # Necesario para que funcione el procesador de contexto
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'gestion_academica.context_processors.datos_institucion_context', # <--- ESTA LÍNEA ES CRUCIAL Y DEBE SER EXACTA
            ],
        },
    },
]

WSGI_APPLICATION = 'proyecto_colegio.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# Configuración de Idioma y Zona Horaria
LANGUAGE_CODE = 'es' # O 'es-co'
TIME_ZONE = 'America/Bogota' # Ajusta a tu zona horaria
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'gestion_academica.Usuario' # Asegúrate que la app se llame 'gestion_academica'
                                              # y el modelo 'Usuario'

STATIC_URL = 'static/'
# STATIC_ROOT = BASE_DIR / 'staticfiles' # Para producción

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media') # BASE_DIR ya está definido por Django                                              

LOGIN_URL = 'login' # Nombre de la URL de login (provista por django.contrib.auth.urls)
LOGIN_REDIRECT_URL = 'gestion_academica:inicio_academico' # A dónde ir después de un login exitoso
# LOGOUT_REDIRECT_URL omitido → Django renderiza registration/logged_out.html con pantalla de despedida


CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5" 
# Para versiones más recientes de crispy-forms, podrías usar:
# CRISPY_DEFAULT_TEMPLATE_PACK = "bootstrap5"
# En general, con las dos primeras líneas suele ser suficiente para empezar.