# Generated by Django 5.2.1 on 2025-07-20 22:45

import admisiones.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aspirante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=150, verbose_name='Nombres Completos')),
                ('apellidos', models.CharField(max_length=150, verbose_name='Apellidos Completos')),
                ('numero_documento', models.CharField(max_length=20, verbose_name='Número de Documento')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('email_contacto', models.EmailField(max_length=254, verbose_name='Email de Contacto Principal')),
                ('telefono_contacto', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de Contacto')),
                ('estado', models.CharField(choices=[('INSCRITO', 'Inscrito / Pendiente de Revisión'), ('EN_PROCESO', 'En Proceso de Admisión'), ('ADMITIDO', 'Admitido'), ('APROBADO_MATRICULA', 'Aprobado para Matrícula'), ('RECHAZADO', 'No Admitido'), ('MATRICULADO', 'Matriculado')], default='INSCRITO', max_length=20)),
                ('requiere_pago_inscripcion', models.BooleanField(default=True)),
                ('colegio_procedencia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Colegio de Procedencia')),
                ('municipio_ciudad', models.CharField(blank=True, max_length=150, null=True, verbose_name='Municipio/Ciudad')),
                ('departamento', models.CharField(blank=True, max_length=150, null=True, verbose_name='Departamento')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('access_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CitaAgendada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agendamiento', models.DateTimeField(auto_now_add=True)),
                ('notas_adicionales', models.TextField(blank=True, help_text='Notas del padre de familia al momento de agendar.')),
                ('estado', models.CharField(choices=[('agendada', 'Agendada'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='agendada', max_length=20)),
            ],
            options={
                'verbose_name': 'Cita Agendada',
                'verbose_name_plural': 'Citas Agendadas',
            },
        ),
        migrations.CreateModel(
            name='DocumentoEntregado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=admisiones.models.ruta_documento_aspirante)),
                ('estado', models.CharField(choices=[('subido', 'Subido por Postulante'), ('en_revision', 'En Revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado - Se requiere nueva carga')], default='subido', max_length=20)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('observaciones_revision', models.TextField(blank=True, help_text="Comentarios del personal de admisiones (ej: 'El documento no es legible').")),
            ],
            options={
                'verbose_name': 'Documento Entregado',
                'verbose_name_plural': 'Documentos Entregados',
            },
        ),
        migrations.CreateModel(
            name='DocumentoRequerido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Documento')),
                ('descripcion', models.TextField(blank=True, help_text='Instrucciones para el padre de familia sobre este documento.')),
                ('es_obligatorio', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Documento Requerido',
                'verbose_name_plural': 'Documentos Requeridos',
            },
        ),
        migrations.CreateModel(
            name='HorarioDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cita', models.CharField(choices=[('entrevista', 'Entrevista con Admisiones'), ('psicologia', 'Entrevista con Psicología'), ('examen', 'Examen de Admisión')], max_length=20)),
                ('fecha_hora_inicio', models.DateTimeField(verbose_name='Fecha y Hora de Inicio')),
                ('duracion_minutos', models.PositiveIntegerField(default=30, help_text='Duración de la cita en minutos.')),
                ('cupos_disponibles', models.PositiveIntegerField(default=1, help_text='Cuántos aspirantes pueden agendarse en este horario (usualmente 1).')),
            ],
            options={
                'verbose_name': 'Horario Disponible para Cita',
                'verbose_name_plural': 'Horarios Disponibles para Citas',
                'ordering': ['fecha_hora_inicio'],
            },
        ),
    ]
