# Generated by Django 5.2.1 on 2025-07-20 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admisiones', '0001_initial'),
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirante',
            name='cuenta_pago_inscripcion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aspirante_inscripcion', to='finanzas.cuentaporcobrarestudiante'),
        ),
    ]
