# Generated by Django 5.2.1 on 2025-07-20 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admisiones', '0002_initial'),
        ('finanzas', '0001_initial'),
        ('gestion_academica', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirante',
            name='estudiante_creado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aspirante_origen', to='gestion_academica.estudiante'),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='grado_aspira',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_academica.grado', verbose_name='Grado al que Aspira'),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aspirantes', to='finanzas.institucioneducativa', verbose_name='Institución a la que aplica'),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_aspirante', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AspiranteConDocumentos',
            fields=[
            ],
            options={
                'verbose_name': 'Revisión de Documento por Aspirante',
                'verbose_name_plural': 'Revisión de Documentos por Aspirante',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('admisiones.aspirante',),
        ),
        migrations.AddField(
            model_name='citaagendada',
            name='aspirante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cita_agendada', to='admisiones.aspirante'),
        ),
        migrations.AddField(
            model_name='citaagendada',
            name='institucion',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='finanzas.institucioneducativa'),
        ),
        migrations.AddField(
            model_name='documentoentregado',
            name='aspirante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_entregados', to='admisiones.aspirante'),
        ),
        migrations.AddField(
            model_name='documentoentregado',
            name='institucion',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='finanzas.institucioneducativa'),
        ),
        migrations.AddField(
            model_name='documentorequerido',
            name='grados_aplicables',
            field=models.ManyToManyField(help_text='Selecciona todos los grados que requieren este documento.', to='gestion_academica.grado', verbose_name='Grados a los que aplica'),
        ),
        migrations.AddField(
            model_name='documentorequerido',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzas.institucioneducativa', verbose_name='Institución que lo requiere'),
        ),
        migrations.AddField(
            model_name='documentoentregado',
            name='documento_requerido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admisiones.documentorequerido'),
        ),
        migrations.AddField(
            model_name='horariodisponible',
            name='entrevistador',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('rol', 'docente'), ('rol', 'coordinador'), ('rol', 'administrador'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Entrevistador/Responsable'),
        ),
        migrations.AddField(
            model_name='horariodisponible',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzas.institucioneducativa', verbose_name='Institución'),
        ),
        migrations.AddField(
            model_name='citaagendada',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas_agendadas', to='admisiones.horariodisponible'),
        ),
        migrations.AlterUniqueTogether(
            name='documentorequerido',
            unique_together={('institucion', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='documentoentregado',
            unique_together={('aspirante', 'documento_requerido')},
        ),
        migrations.AlterUniqueTogether(
            name='horariodisponible',
            unique_together={('institucion', 'fecha_hora_inicio', 'tipo_cita')},
        ),
    ]
