# Generated by Django 5.2.1 on 2026-05-13 00:11

import admisiones.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admisiones', '0003_initial'),
        ('finanzas', '0007_auditoriaexportacioncontable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteImportacionAspirantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=admisiones.models._ruta_archivo_lote_importacion, verbose_name='Archivo Excel')),
                ('nombre_original', models.CharField(blank=True, max_length=255, verbose_name='Nombre original')),
                ('dry_run', models.BooleanField(default=False, help_text='Cuando está marcado, valida y reporta errores sin persistir aspirantes.', verbose_name='Modo simulación (no crea registros)')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de procesar'), ('EN_PROCESO', 'En proceso'), ('COMPLETADO', 'Completado'), ('FALLIDO', 'Fallido'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('total_filas', models.PositiveIntegerField(default=0)),
                ('filas_procesadas', models.PositiveIntegerField(default=0)),
                ('filas_exitosas', models.PositiveIntegerField(default=0)),
                ('filas_fallidas', models.PositiveIntegerField(default=0)),
                ('errores', models.JSONField(blank=True, default=list, help_text='Lista de diccionarios: {fila, documento, error}.', verbose_name='Errores por fila')),
                ('mensaje_error_general', models.TextField(blank=True, verbose_name='Mensaje de error general')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_importacion_aspirantes_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes_importacion_aspirantes', to='finanzas.institucioneducativa', verbose_name='Institución')),
            ],
            options={
                'verbose_name': 'Lote de importación de aspirantes',
                'verbose_name_plural': 'Lotes de importación de aspirantes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='aspirante',
            name='lote_importacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aspirantes_creados', to='admisiones.loteimportacionaspirantes', verbose_name='Lote de importación de origen'),
        ),
        migrations.AddIndex(
            model_name='loteimportacionaspirantes',
            index=models.Index(fields=['institucion', '-fecha_creacion'], name='admisiones__institu_33b0ba_idx'),
        ),
        migrations.AddIndex(
            model_name='loteimportacionaspirantes',
            index=models.Index(fields=['estado'], name='admisiones__estado_f464fb_idx'),
        ),
    ]
