# Generated by Django 5.2.1 on 2026-05-13 00:27

from django.conf import settings
from django.db import migrations, models
from django.db.models import Count


def _abortar_si_hay_duplicados(apps, schema_editor):
    """Antes de añadir la UNIQUE, asegura que no haya documentos duplicados
    dentro de la misma institución (esta plataforma es SaaS multi-institución).

    Si encuentra conflictos, aborta con un mensaje accionable indicando que
    hay que limpiar los datos antes (ver
    ``manage.py detectar_duplicados_aspirantes``).
    """
    Aspirante = apps.get_model('admisiones', 'Aspirante')
    duplicados = (
        Aspirante.objects
        .exclude(numero_documento__isnull=True)
        .exclude(numero_documento__exact='')
        .values('institucion_id', 'numero_documento')
        .annotate(total=Count('id'))
        .filter(total__gt=1)
    )
    conflictos = list(duplicados[:25])
    if not conflictos:
        return

    detalle = '; '.join(
        f"institucion={c['institucion_id']} doc={c['numero_documento']} ({c['total']})"
        for c in conflictos
    )
    raise RuntimeError(
        "No se puede aplicar la UniqueConstraint(institucion, numero_documento): "
        "existen documentos duplicados dentro de una o más instituciones. "
        "Ejecuta primero: `python manage.py detectar_duplicados_aspirantes` "
        "para ver el detalle y limpiar los datos. Conflictos (muestra): " + detalle
    )


class Migration(migrations.Migration):

    dependencies = [
        ('admisiones', '0004_lote_importacion_aspirantes'),
        ('finanzas', '0007_auditoriaexportacioncontable'),
        ('gestion_academica', '0021_alter_periodoacademico_año_escolar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            _abortar_si_hay_duplicados,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterModelOptions(
            name='aspirante',
            options={'ordering': ['-fecha_inscripcion'], 'verbose_name': 'Aspirante', 'verbose_name_plural': 'Aspirantes'},
        ),
        migrations.AddField(
            model_name='loteimportacionaspirantes',
            name='cancelacion_solicitada',
            field=models.BooleanField(default=False, help_text='Marcado por el usuario al pedir cancelar. La tarea verifica este flag entre filas y termina limpiamente.', verbose_name='Cancelación solicitada'),
        ),
        migrations.AddField(
            model_name='loteimportacionaspirantes',
            name='task_id',
            field=models.CharField(blank=True, help_text='UUID de la tarea Celery que procesa este lote (necesario para revoke).', max_length=255, verbose_name='ID de tarea Celery'),
        ),
        migrations.AddIndex(
            model_name='aspirante',
            index=models.Index(fields=['institucion', 'estado'], name='admisiones__institu_6638c6_idx'),
        ),
        migrations.AddIndex(
            model_name='aspirante',
            index=models.Index(fields=['institucion', 'numero_documento'], name='admisiones__institu_4ea819_idx'),
        ),
        migrations.AddConstraint(
            model_name='aspirante',
            constraint=models.UniqueConstraint(condition=models.Q(('numero_documento', ''), _negated=True), fields=('institucion', 'numero_documento'), name='aspirante_unico_doc_por_institucion'),
        ),
    ]
