# Generated by Django 5.2.1 on 2026-05-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admisiones', '0006_lote_filas_con_advertencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='loteimportacionaspirantes',
            name='resumen_correos',
            field=models.JSONField(blank=True, default=None, help_text='Almacena el resultado del último envío/reenvío masivo de correos: {tipo, fecha, ok, errores_count, omitidos, total, detalle_errores[]}.', null=True, verbose_name='Resumen del último envío de correos'),
        ),
    ]
