# Generated by Django 5.2.15 on 2026-06-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admisiones", "0009_loteimportacionaspirantes_archivo_bytes"),
    ]

    operations = [
        migrations.AddField(
            model_name="aspirante",
            name="apoyo_academico_especial",
            field=models.BooleanField(
                default=False, verbose_name="¿Requiere apoyo académico especial?"
            ),
        ),
        migrations.AddField(
            model_name="aspirante",
            name="capacidad_excepcional",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NINGUNA", "Ninguna"),
                    ("GLOBAL", "Capacidad excepcional global"),
                    ("TALENTO_CIENTIFICO", "Talento científico/tecnológico"),
                    ("TALENTO_ARTISTICO", "Talento artístico"),
                    ("TALENTO_DEPORTIVO", "Talento deportivo"),
                    ("OTRA", "Otra"),
                ],
                max_length=25,
                null=True,
                verbose_name="Capacidad / talento excepcional",
            ),
        ),
        migrations.AddField(
            model_name="aspirante",
            name="discapacidad_categoria",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NINGUNA", "Ninguna"),
                    ("FISICA", "Física (movilidad)"),
                    ("INTELECTUAL", "Intelectual / cognitiva"),
                    ("PSICOSOCIAL", "Psicosocial (mental)"),
                    ("VISUAL_BAJA", "Visual — baja visión"),
                    ("VISUAL_CEGUERA", "Visual — ceguera"),
                    ("AUDITIVA_HIPOACUSIA", "Auditiva — hipoacusia"),
                    ("AUDITIVA_SORDA", "Auditiva — sordera"),
                    ("SORDOCEGUERA", "Sordoceguera"),
                    ("MULTIPLE", "Múltiple"),
                    ("SISTEMICA", "Sistémica"),
                    ("VOZ_Y_HABLA", "De la voz y el habla"),
                    ("TEA", "Trastorno del espectro autista"),
                    ("OTRA", "Otra"),
                ],
                max_length=25,
                null=True,
                verbose_name="Categoría de discapacidad (MEN)",
            ),
        ),
        migrations.AddField(
            model_name="aspirante",
            name="estrato",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0", "Sin estrato"),
                    ("1", "Estrato 1"),
                    ("2", "Estrato 2"),
                    ("3", "Estrato 3"),
                    ("4", "Estrato 4"),
                    ("5", "Estrato 5"),
                    ("6", "Estrato 6"),
                ],
                max_length=1,
                null=True,
                verbose_name="Estrato socioeconómico",
            ),
        ),
        migrations.AddField(
            model_name="aspirante",
            name="grupo_etnico",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NINGUNO", "Ninguno"),
                    ("INDIGENA", "Indígena"),
                    ("AFROCOLOMBIANO", "Afrocolombiano / negro"),
                    ("RAIZAL", "Raizal (San Andrés)"),
                    ("PALENQUERO", "Palenquero (San Basilio)"),
                    ("ROM", "ROM (gitano)"),
                ],
                max_length=20,
                null=True,
                verbose_name="Grupo étnico",
            ),
        ),
        migrations.AddField(
            model_name="aspirante",
            name="pais_origen",
            field=models.CharField(
                blank=True,
                help_text="Para aspirantes migrantes. Dejar en blanco si es Colombia.",
                max_length=100,
                null=True,
                verbose_name="País de origen",
            ),
        ),
        migrations.AddField(
            model_name="aspirante",
            name="regimen_salud",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CONTRIBUTIVO", "Contributivo"),
                    ("SUBSIDIADO", "Subsidiado"),
                    ("ESPECIAL", "Especial / Excepción"),
                    ("NO_AFILIADO", "No afiliado / Vinculado"),
                ],
                max_length=15,
                null=True,
                verbose_name="Régimen de salud",
            ),
        ),
        migrations.AddField(
            model_name="aspirante",
            name="sisben_grupo",
            field=models.CharField(
                blank=True,
                help_text="Clasificación SISBÉN IV (ej: A1, B2, C3).",
                max_length=10,
                null=True,
                verbose_name="Grupo SISBÉN",
            ),
        ),
        migrations.AddField(
            model_name="aspirante",
            name="sisben_puntaje",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Puntaje SISBÉN",
            ),
        ),
        migrations.AddField(
            model_name="aspirante",
            name="srpa",
            field=models.BooleanField(
                default=False,
                verbose_name="¿Sistema de Responsabilidad Penal Adolescente (SRPA)?",
            ),
        ),
        migrations.AddField(
            model_name="aspirante",
            name="tipo_poblacion_victima",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DESPLAZADO", "Desplazado"),
                    ("VICTIMA_MINAS", "Víctima de minas antipersona"),
                    ("DESVINCULADO", "Desvinculado de grupos armados"),
                    ("HIJO_DESMOVILIZADO", "Hijo de adulto desmovilizado"),
                    ("OTRA", "Otra"),
                ],
                max_length=20,
                null=True,
                verbose_name="Tipo de población víctima",
            ),
        ),
        migrations.AddField(
            model_name="aspirante",
            name="victima_conflicto",
            field=models.BooleanField(
                default=False, verbose_name="¿Víctima del conflicto armado?"
            ),
        ),
        migrations.AddField(
            model_name="aspirante",
            name="zona_residencia",
            field=models.CharField(
                blank=True,
                choices=[("URBANA", "Urbana"), ("RURAL", "Rural")],
                max_length=10,
                null=True,
                verbose_name="Zona de residencia",
            ),
        ),
    ]
