# Generated by Django 5.2.1 on 2026-09-02 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admisiones", "0015_tipo_documento_max_length"),
        ("gestion_academica", "0078_enfasis_taller_tecnico"),
    ]

    operations = [
        migrations.AddField(
            model_name="aspirante",
            name="enfasis",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="aspirantes",
                to="gestion_academica.enfasis",
                verbose_name="Énfasis / Taller (media técnica)",
            ),
        ),
    ]
