# Generated by Django 5.2.1 on 2025-07-23 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacionlogro',
            name='logro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='gestion_academica.descriptorlogro'),
        ),
    ]
