# Generated by Django 5.2.1 on 2025-07-23 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_cuentacontable_institucion_and_more'),
        ('gestion_academica', '0002_alter_evaluacionlogro_logro'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimensionDesarrollo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Dimensión')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición en los reportes')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzas.institucioneducativa')),
            ],
            options={
                'verbose_name': 'Dimensión de Desarrollo (Preescolar)',
                'verbose_name_plural': 'Dimensiones de Desarrollo (Preescolar)',
                'ordering': ['orden', 'nombre'],
                'unique_together': {('institucion', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='descriptorlogro',
            name='dimension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logros', to='gestion_academica.dimensiondesarrollo'),
        ),
    ]
