# Generated by Django 5.2.1 on 2025-07-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0003_dimensiondesarrollo_descriptorlogro_dimension'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimensiondesarrollo',
            name='materias',
            field=models.ManyToManyField(blank=True, related_name='dimensiones', to='gestion_academica.materia', verbose_name='Materias Incluidas en esta Dimensión'),
        ),
    ]
