# Generated by Django 5.2.1 on 2025-07-23 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0004_dimensiondesarrollo_materias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacionlogro',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_academica.escalacualitativa'),
        ),
        migrations.AlterField(
            model_name='evaluacionlogro',
            name='logro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='gestion_academica.logro'),
        ),
    ]
