# Generated by Django 5.2.1 on 2025-07-24 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_cuentacontable_institucion_and_more'),
        ('gestion_academica', '0005_alter_evaluacionlogro_estado_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EvaluacionLogro',
            new_name='EvaluacionLogroPreescolar',
        ),
        migrations.AlterModelOptions(
            name='evaluacionlogropreescolar',
            options={'verbose_name': 'Evaluación de Logro (Preescolar)', 'verbose_name_plural': 'Evaluaciones de Logros (Preescolar)'},
        ),
        migrations.CreateModel(
            name='LogroPreescolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Descripción del Logro')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición dentro de la materia.')),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logros_preescolar', to='gestion_academica.dimensiondesarrollo', verbose_name='Dimensión de Desarrollo')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzas.institucioneducativa')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logros_preescolar', to='gestion_academica.materia', verbose_name='Materia Asociada')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logros_preescolar', to='gestion_academica.periodoacademico', verbose_name='Periodo Académico')),
            ],
            options={
                'verbose_name': 'Logro de Preescolar',
                'verbose_name_plural': 'Logros de Preescolar',
                'ordering': ['dimension__orden', 'materia__nombre_materia', 'orden'],
            },
        ),
    ]
