# Generated by Django 5.2.1 on 2025-07-24 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0006_rename_evaluacionlogro_evaluacionlogropreescolar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacionlogropreescolar',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_logros_preescolar', to='gestion_academica.estudiante'),
        ),
        migrations.AlterField(
            model_name='evaluacionlogropreescolar',
            name='logro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='gestion_academica.logropreescolar'),
        ),
    ]
