# Generated by Django 5.2.1 on 2025-07-24 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0007_alter_evaluacionlogropreescolar_estudiante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalacualitativa',
            name='es_reprobatoria',
            field=models.BooleanField(default=False, help_text="Marcar solo para el nivel más bajo (ej: 'Bajo', 'Insuficiente').", verbose_name='¿Este nivel se considera reprobatorio?'),
        ),
    ]
