# Generated by Django 5.2.1 on 2025-07-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0008_escalacualitativa_es_reprobatoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='google_calendar_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID del Calendario de Google Sincronizado'),
        ),
    ]
