# Generated by Django 5.2.1 on 2025-07-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0009_usuario_google_calendar_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloquehorario',
            name='google_event_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID del Evento en Google Calendar'),
        ),
    ]
