# Generated by Django 5.2.1 on 2025-07-30 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_cuentacontable_institucion_and_more'),
        ('gestion_academica', '0011_ticketsoporte_respuestaticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaneacionClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título de la Unidad o Tema')),
                ('metodologia', models.CharField(choices=[('PROYECTOS', 'Aprendizaje Basado en Proyectos (ABP)'), ('PROBLEMAS', 'Aprendizaje Basado en Problemas (ABP)'), ('INVERTIDA', 'Aula Invertida'), ('TRADICIONAL', 'Clase Magistral / Tradicional'), ('COLABORATIVO', 'Aprendizaje Colaborativo'), ('GAMIFICACION', 'Gamificación')], max_length=20, verbose_name='Metodología Principal')),
                ('duracion_clases', models.PositiveIntegerField(default=1, verbose_name='Número de Clases de Duración')),
                ('objetivos_aprendizaje', models.TextField(blank=True, null=True, verbose_name='Objetivos de Aprendizaje')),
                ('recursos_necesarios', models.TextField(blank=True, null=True, verbose_name='Recursos Necesarios')),
                ('criterios_evaluacion', models.TextField(blank=True, null=True, verbose_name='Criterios de Evaluación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planeaciones', to='gestion_academica.curso')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planeaciones', to='gestion_academica.docente')),
                ('institucion', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='finanzas.institucioneducativa')),
            ],
            options={
                'verbose_name': 'Planeación de Clase',
                'verbose_name_plural': 'Planeaciones de Clases',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DetalleClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_clase', models.PositiveIntegerField(verbose_name='Número de Clase')),
                ('tema_clase', models.CharField(max_length=255, verbose_name='Tema de la Clase')),
                ('actividades_inicio', models.TextField(verbose_name='Actividades de Inicio')),
                ('actividades_desarrollo', models.TextField(verbose_name='Actividades de Desarrollo')),
                ('actividades_cierre', models.TextField(verbose_name='Actividades de Cierre')),
                ('planeacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_clase', to='gestion_academica.planeacionclase')),
            ],
            options={
                'verbose_name': 'Detalle de Clase',
                'verbose_name_plural': 'Detalles de Clases',
                'ordering': ['numero_clase'],
                'unique_together': {('planeacion', 'numero_clase')},
            },
        ),
    ]
