# Generated by Django 5.2.1 on 2025-07-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0012_planeacionclase_detalleclase'),
    ]

    operations = [
        migrations.AddField(
            model_name='planeacionclase',
            name='error_generacion',
            field=models.TextField(blank=True, null=True, verbose_name='Mensaje de Error (si falló)'),
        ),
        migrations.AddField(
            model_name='planeacionclase',
            name='estado_generacion',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Generación'), ('GENERANDO', 'Generando Contenido con IA'), ('COMPLETADO', 'Completado Exitosamente'), ('FALLIDO', 'Falló la Generación')], default='PENDIENTE', max_length=20, verbose_name='Estado de Generación IA'),
        ),
    ]
