# Generated by Django 5.2.1 on 2025-07-30 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0013_planeacionclase_error_generacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planeacionclase',
            name='ultima_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
