# Generated by Django 5.2.1 on 2025-08-01 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0014_planeacionclase_ultima_actualizacion'),
    ]

    operations = [
        # --- INICIO DE LA CORRECCIÓN ---
        # 1. Primero, eliminamos los campos antiguos del modelo Candidato.
        migrations.RemoveField(
            model_name='candidato',
            name='grado',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='institucion',
        ),
        migrations.RemoveField(
            model_name='voto',
            name='institucion',
        ),

        # 2. Luego, añadimos el nuevo campo 'estudiante' a Candidato.
        migrations.AddField(
            model_name='candidato',
            name='estudiante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='gestion_academica.estudiante'),
            preserve_default=False,
        ),

        # 3. Ahora que el campo 'estudiante' existe, aplicamos la regla 'unique_together'.
        migrations.AlterUniqueTogether(
            name='candidato',
            unique_together={('eleccion', 'estudiante')},
        ),
        
        # 4. Finalmente, realizamos las demás alteraciones que son seguras.
        migrations.AlterModelOptions(
            name='voto',
            options={'verbose_name': 'Voto', 'verbose_name_plural': 'Votos'},
        ),
        migrations.AlterField(
            model_name='candidato',
            name='eleccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatos', to='gestion_academica.eleccion'),
        ),
        migrations.AlterField(
            model_name='voto',
            name='candidato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos_recibidos', to='gestion_academica.candidato'),
        ),
        migrations.AlterField(
            model_name='voto',
            name='eleccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='gestion_academica.eleccion'),
        ),
        migrations.AlterField(
            model_name='voto',
            name='votante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos_emitidos', to='gestion_academica.estudiante'),
        ),
        # --- FIN DE LA CORRECCIÓN ---
    ]
