# Generated by Django 5.2.1 on 2025-08-01 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0015_alter_voto_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bloquehorario',
            unique_together=set(),
        ),
    ]
