# Generated by Django 5.2.1 on 2025-08-02 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0016_alter_bloquehorario_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivoplanacademico',
            name='temas_relacionados',
            field=models.TextField(blank=True, help_text="Añade temas específicos separados por comas (ej: 'Suma de fracciones', 'Teorema de Pitágoras', 'Análisis de personajes').", null=True, verbose_name='Temas Relevantes'),
        ),
    ]
