# Generated by Django 5.2.1 on 2025-08-03 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_cuentacontable_institucion_and_more'),
        ('gestion_academica', '0017_archivoplanacademico_temas_relacionados'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisComportamientoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumen_ia', models.TextField(verbose_name='Análisis y Resumen de la IA')),
                ('patrones_detectados', models.JSONField(blank=True, null=True, verbose_name='Patrones Estructurados')),
                ('fecha_analisis', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Análisis')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis_comportamiento', to='gestion_academica.estudiante')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzas.institucioneducativa')),
            ],
            options={
                'verbose_name': 'Análisis de Comportamiento (IA)',
                'verbose_name_plural': 'Análisis de Comportamiento (IA)',
                'ordering': ['-fecha_analisis'],
            },
        ),
    ]
