# Generated by Django 5.2.1 on 2025-08-04 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0018_analisiscomportamientoia'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregadeber',
            name='alerta_plagio',
            field=models.BooleanField(default=False, verbose_name='Alerta de Posible Plagio'),
        ),
        migrations.AddField(
            model_name='entregadeber',
            name='porcentaje_similitud',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Porcentaje de Similitud (%)'),
        ),
    ]
