# Generated by Django 5.2.1 on 2025-08-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0019_entregadeber_alerta_plagio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='dashboard_layout',
            field=models.JSONField(blank=True, null=True, verbose_name='Diseño del Dashboard'),
        ),
    ]
