# Generated by Django 5.2.1 on 2026-02-28 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0020_docente_dashboard_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodoacademico',
            name='año_escolar',
            field=models.PositiveIntegerField(default=2026, verbose_name='Año Escolar'),
        ),
    ]
