# Generated by Django 5.2.1 on 2026-05-15 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0011_ejecucionhealthcheck'),
        ('gestion_academica', '0024_asignar_permisos_portal_familiar_existentes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasoConvivencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radicado', models.CharField(editable=False, help_text='Generado automáticamente: CONV-AAAA-NNNN', max_length=20, unique=True, verbose_name='Número de radicado')),
                ('tipo_situacion', models.CharField(choices=[('TIPO I', 'Tipo I — Conflicto menor'), ('TIPO II', 'Tipo II — Daño moderado'), ('TIPO III', 'Tipo III — Daño grave / delito')], max_length=10, verbose_name='Tipo de situación (Res. 1620)')),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('EN_SEGUIMIENTO', 'En seguimiento'), ('VENCIDO', 'Vencido — plazo superado'), ('CERRADO', 'Cerrado'), ('ARCHIVADO', 'Archivado')], default='ABIERTO', max_length=15, verbose_name='Estado del caso')),
                ('descripcion_detalle', models.TextField(help_text='Completar o ampliar la descripción inicial.', verbose_name='Descripción detallada del hecho')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_limite', models.DateTimeField(blank=True, null=True, verbose_name='Fecha límite legal de respuesta')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('protocolo_ia', models.TextField(blank=True, verbose_name='Protocolo sugerido por IA')),
                ('resolucion_final', models.TextField(blank=True, help_text='Completar al cerrar el caso.', verbose_name='Resolución y compromisos finales')),
                ('anotacion_origen', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caso_convivencia', to='gestion_academica.anotacionobservador', verbose_name='Anotación que originó el caso')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos_convivencia', to='finanzas.institucioneducativa')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_convivencia_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Coordinador responsable')),
            ],
            options={
                'verbose_name': 'Caso de Convivencia',
                'verbose_name_plural': 'Casos de Convivencia',
                'ordering': ['-fecha_apertura'],
                'permissions': [('puede_gestionar_casos', 'Puede gestionar casos de convivencia (Sentinel)')],
            },
        ),
        migrations.CreateModel(
            name='AccionCaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_accion', models.CharField(choices=[('NOTIFICACION_PADRE', 'Notificación a padre/tutor'), ('REUNION_COMITE', 'Reunión de Comité de Convivencia'), ('REPORTE_AUTORIDAD', 'Reporte a autoridad externa (ICBF / Policía)'), ('ACUERDO_COMPROMISO', 'Acuerdo y compromisos firmados'), ('SEGUIMIENTO', 'Seguimiento periódico'), ('MEDIACION', 'Proceso de mediación escolar'), ('REMISION_PROFESIONAL', 'Remisión a profesional externo'), ('CIERRE', 'Cierre formal del caso'), ('OTRO', 'Otra acción')], max_length=25, verbose_name='Tipo de acción')),
                ('descripcion', models.TextField(verbose_name='Descripción de lo actuado')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('evidencia', models.FileField(blank=True, null=True, upload_to='sentinel/evidencias/%Y/%m/', verbose_name='Evidencia / documento adjunto')),
                ('ejecutado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_caso', to=settings.AUTH_USER_MODEL, verbose_name='Ejecutado por')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones', to='gestion_academica.casoconvivencia')),
            ],
            options={
                'verbose_name': 'Acción sobre caso',
                'verbose_name_plural': 'Acciones sobre casos',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='InvolucradoCaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('VICTIMA', 'Víctima'), ('AGRESOR', 'Agresor/a'), ('TESTIGO', 'Testigo'), ('OTRO', 'Otro involucrado')], max_length=10)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='involucrados', to='gestion_academica.casoconvivencia')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos_involucrado', to='gestion_academica.estudiante')),
            ],
            options={
                'verbose_name': 'Involucrado en caso',
                'verbose_name_plural': 'Involucrados en caso',
                'unique_together': {('caso', 'estudiante')},
            },
        ),
    ]
