# Generated by Django 5.2.1 on 2026-05-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0025_sentinel_convivencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/', verbose_name='Foto de Perfil'),
        ),
    ]
