# Generated by Django 5.2.1 on 2026-05-19 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0011_ejecucionhealthcheck'),
        ('gestion_academica', '0026_add_foto_perfil_to_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='MallaCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año_lectivo', models.PositiveIntegerField(default=2026, verbose_name='Año Lectivo')),
                ('descripcion_general', models.TextField(blank=True, null=True, verbose_name='Propósitos Generales / Descripción')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mallas_creadas', to=settings.AUTH_USER_MODEL)),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mallas_curriculares', to='gestion_academica.grado', verbose_name='Grado')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzas.institucioneducativa', verbose_name='Institución')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mallas_curriculares', to='gestion_academica.materia', verbose_name='Materia')),
            ],
            options={
                'verbose_name': 'Malla Curricular',
                'verbose_name_plural': 'Mallas Curriculares',
                'ordering': ['grado__orden', 'materia__nombre_materia'],
                'unique_together': {('materia', 'grado', 'año_lectivo', 'institucion')},
            },
        ),
        migrations.CreateModel(
            name='ItemMalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.PositiveSmallIntegerField(choices=[(1, '1° Período'), (2, '2° Período'), (3, '3° Período'), (4, '4° Período')], verbose_name='Período')),
                ('mes', models.PositiveSmallIntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], verbose_name='Mes')),
                ('semana_del_mes', models.PositiveSmallIntegerField(choices=[(1, 'Semana 1'), (2, 'Semana 2'), (3, 'Semana 3'), (4, 'Semana 4'), (5, 'Semana 5')], verbose_name='Semana del Mes')),
                ('tema', models.CharField(max_length=255, verbose_name='Tema / Contenido')),
                ('logro_esperado', models.TextField(verbose_name='Logro / Estándar Esperado')),
                ('competencias', models.TextField(blank=True, null=True, verbose_name='Competencias / Indicadores')),
                ('recursos', models.TextField(blank=True, null=True, verbose_name='Recursos Sugeridos')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('malla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gestion_academica.mallacurricular')),
            ],
            options={
                'verbose_name': 'Ítem de Malla',
                'verbose_name_plural': 'Ítems de Malla',
                'ordering': ['periodo', 'mes', 'semana_del_mes', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='PlanSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana_inicio', models.DateField(verbose_name='Inicio de Semana (Lunes)')),
                ('semana_fin', models.DateField(verbose_name='Fin de Semana (Viernes)')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADO', 'Enviado al Coordinador'), ('APROBADO', 'Aprobado'), ('CON_OBSERVACIONES', 'Con Observaciones')], default='BORRADOR', max_length=20)),
                ('observaciones_coordinador', models.TextField(blank=True, null=True, verbose_name='Observaciones del Coordinador')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_semanales', to='gestion_academica.curso')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_semanales', to='gestion_academica.docente')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzas.institucioneducativa')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_revisados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan Semanal',
                'verbose_name_plural': 'Planes Semanales',
                'ordering': ['-semana_inicio'],
                'unique_together': {('docente', 'curso', 'semana_inicio')},
            },
        ),
        migrations.CreateModel(
            name='ItemPlanSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de la Clase')),
                ('titulo', models.CharField(max_length=255, verbose_name='Tema / Título')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción / Actividades')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('actividad', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_plan_origen', to='gestion_academica.actividadcalificable')),
                ('deber', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_plan_origen', to='gestion_academica.deber')),
                ('item_malla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_plan', to='gestion_academica.itemmalla', verbose_name='Ítem de Malla Vinculado')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gestion_academica.plansemanal')),
            ],
            options={
                'verbose_name': 'Ítem de Plan Semanal',
                'verbose_name_plural': 'Ítems de Plan Semanal',
                'ordering': ['fecha', 'orden'],
            },
        ),
    ]
