# Generated by Django 5.2.1 on 2026-05-19 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0027_malla_curricular_plan_semanal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemmalla',
            options={'ordering': ['periodo', 'orden'], 'verbose_name': 'Ítem de Malla', 'verbose_name_plural': 'Ítems de Malla'},
        ),
        migrations.RemoveField(
            model_name='itemmalla',
            name='logro_esperado',
        ),
        migrations.RemoveField(
            model_name='itemmalla',
            name='mes',
        ),
        migrations.RemoveField(
            model_name='itemmalla',
            name='semana_del_mes',
        ),
        migrations.RemoveField(
            model_name='itemmalla',
            name='tema',
        ),
        migrations.AddField(
            model_name='itemmalla',
            name='dba',
            field=models.TextField(blank=True, null=True, verbose_name='Derechos Básicos de Aprendizaje (DBA)'),
        ),
        migrations.AddField(
            model_name='itemmalla',
            name='ebc',
            field=models.TextField(blank=True, null=True, verbose_name='Estándares Básicos de Competencias (EBC)'),
        ),
        migrations.AddField(
            model_name='itemmalla',
            name='eje_tematico',
            field=models.CharField(default='', max_length=255, verbose_name='Eje Temático / Contenido'),
        ),
        migrations.AddField(
            model_name='itemmalla',
            name='evaluacion',
            field=models.TextField(blank=True, null=True, verbose_name='Criterios de Evaluación'),
        ),
        migrations.AddField(
            model_name='itemmalla',
            name='indicador_alto',
            field=models.TextField(blank=True, null=True, verbose_name='Indicador — Desempeño Alto (4.0–4.5)'),
        ),
        migrations.AddField(
            model_name='itemmalla',
            name='indicador_bajo',
            field=models.TextField(blank=True, null=True, verbose_name='Indicador — Desempeño Bajo (1.0–2.9)'),
        ),
        migrations.AddField(
            model_name='itemmalla',
            name='indicador_basico',
            field=models.TextField(blank=True, null=True, verbose_name='Indicador — Desempeño Básico (3.0–3.9)'),
        ),
        migrations.AddField(
            model_name='itemmalla',
            name='indicador_superior',
            field=models.TextField(blank=True, null=True, verbose_name='Indicador — Desempeño Superior (4.6–5.0)'),
        ),
        migrations.AddField(
            model_name='itemmalla',
            name='logro',
            field=models.TextField(default='', verbose_name='Logro del Período'),
        ),
        migrations.AddField(
            model_name='itemmalla',
            name='metodologia',
            field=models.TextField(blank=True, null=True, verbose_name='Metodología / Estrategias Pedagógicas'),
        ),
        migrations.AddField(
            model_name='itemmalla',
            name='tiempo_semanas',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Duración (semanas del período)'),
        ),
        migrations.AlterField(
            model_name='itemmalla',
            name='competencias',
            field=models.TextField(blank=True, null=True, verbose_name='Competencias'),
        ),
        migrations.AlterField(
            model_name='itemmalla',
            name='recursos',
            field=models.TextField(blank=True, null=True, verbose_name='Recursos'),
        ),
    ]
