# Generated by Django 5.2.1 on 2026-05-21 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0011_ejecucionhealthcheck'),
        ('gestion_academica', '0029_corte_preventivo'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cortepreventivo',
            name='unique_corte_grado_fecha',
        ),
        migrations.RemoveConstraint(
            model_name='detallemateriacorteprev',
            name='unique_detalle_materia_corte',
        ),
        migrations.RemoveConstraint(
            model_name='resultadocorteestudiante',
            name='unique_resultado_corte_estudiante',
        ),
        migrations.AlterField(
            model_name='configuracioncortepreventivo',
            name='porcentaje_inasistencia_alerta',
            field=models.PositiveIntegerField(default=20, help_text='Si el porcentaje de clases perdidas supera este valor, se activa alerta de asistencia. Ej: 20 = 20%', verbose_name='% Inasistencia que genera alerta'),
        ),
        migrations.AlterField(
            model_name='configuracioncortepreventivo',
            name='umbral_riesgo_bajo',
            field=models.DecimalField(decimal_places=2, default=2.9, help_text='Estudiantes con promedio menor a este valor se marcan en RIESGO ALTO. Ej: 2.9', max_digits=4, verbose_name='Umbral Riesgo Alto (nota por debajo de...)'),
        ),
        migrations.AlterField(
            model_name='configuracioncortepreventivo',
            name='umbral_riesgo_medio',
            field=models.DecimalField(decimal_places=2, default=3.4, help_text='Estudiantes entre el umbral alto y este valor se marcan en RIESGO MEDIO. Ej: 3.4', max_digits=4, verbose_name='Umbral Riesgo Medio (nota por debajo de...)'),
        ),
        migrations.AlterField(
            model_name='cortepreventivo',
            name='fecha_corte',
            field=models.DateField(help_text='Fecha hasta la cual se toman en cuenta las actividades y calificaciones', verbose_name='Fecha de Corte'),
        ),
        migrations.AlterField(
            model_name='cortepreventivo',
            name='nombre_corte',
            field=models.CharField(help_text='Ej: Corte 1 – Mayo 2025', max_length=150, verbose_name='Nombre del Corte'),
        ),
        migrations.AlterField(
            model_name='cortepreventivo',
            name='observacion_general',
            field=models.TextField(blank=True, help_text='Mensaje del coordinador para todos los estudiantes del grado', verbose_name='Observación General del Coordinador'),
        ),
        migrations.AlterUniqueTogether(
            name='cortepreventivo',
            unique_together={('institucion', 'periodo_academico', 'grado', 'fecha_corte')},
        ),
        migrations.AlterUniqueTogether(
            name='detallemateriacorteprev',
            unique_together={('resultado_estudiante', 'curso', 'institucion')},
        ),
        migrations.AlterUniqueTogether(
            name='resultadocorteestudiante',
            unique_together={('corte', 'estudiante', 'institucion')},
        ),
    ]
