# Generated by Django 5.2.1 on 2026-05-28 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0033_noticia_banner_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='acudiente_responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes_responsable', to='gestion_academica.familiar', verbose_name='Acudiente responsable (facturación)'),
        ),
    ]
