# Generated by Django 5.2.1 on 2026-06-01 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0034_estudiante_acudiente_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmalla',
            name='competencias_L2',
            field=models.TextField(blank=True, null=True, verbose_name='Competencias (Idioma Secundario)'),
        ),
        migrations.AddField(
            model_name='itemmalla',
            name='eje_tematico_L2',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Eje Temático (Idioma Secundario)'),
        ),
        migrations.AddField(
            model_name='itemmalla',
            name='indicador_alto_L2',
            field=models.TextField(blank=True, null=True, verbose_name='Indicador Alto (Idioma Secundario)'),
        ),
        migrations.AddField(
            model_name='itemmalla',
            name='indicador_bajo_L2',
            field=models.TextField(blank=True, null=True, verbose_name='Indicador Bajo (Idioma Secundario)'),
        ),
        migrations.AddField(
            model_name='itemmalla',
            name='indicador_basico_L2',
            field=models.TextField(blank=True, null=True, verbose_name='Indicador Básico (Idioma Secundario)'),
        ),
        migrations.AddField(
            model_name='itemmalla',
            name='indicador_superior_L2',
            field=models.TextField(blank=True, null=True, verbose_name='Indicador Superior (Idioma Secundario)'),
        ),
        migrations.AddField(
            model_name='itemmalla',
            name='logro_L2',
            field=models.TextField(blank=True, default='', verbose_name='Logro del Período (Idioma Secundario)'),
        ),
        migrations.AddField(
            model_name='materia',
            name='idioma_instruccion',
            field=models.CharField(choices=[('es', 'Español'), ('en', 'Inglés'), ('fr', 'Francés'), ('pt', 'Portugués'), ('de', 'Alemán'), ('zh', 'Mandarín')], default='es', help_text='Idioma en que se dicta esta materia.', max_length=5, verbose_name='Idioma de Instrucción'),
        ),
        migrations.AddField(
            model_name='materia',
            name='nombre_idioma_secundario',
            field=models.CharField(blank=True, default='', help_text="Ej: 'Mathematics', 'Natural Sciences'. Solo visible en colegios bilingües.", max_length=100, verbose_name='Nombre en Idioma Secundario'),
        ),
    ]
