# Generated by Django 5.2.15 on 2026-06-16 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0017_alter_institucioneducativa_brevo_sender_email_and_more"),
        ("gestion_academica", "0040_periodoacademico_cierre_notas"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaracterizacionEstudiante",
            fields=[
                (
                    "estudiante",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="caracterizacion",
                        serialize=False,
                        to="gestion_academica.estudiante",
                        verbose_name="Estudiante",
                    ),
                ),
                (
                    "pais_origen",
                    models.CharField(
                        blank=True,
                        help_text="Para estudiantes migrantes (ej: Venezuela). Dejar en blanco si es Colombia.",
                        max_length=100,
                        null=True,
                        verbose_name="País de origen",
                    ),
                ),
                (
                    "zona_residencia",
                    models.CharField(
                        blank=True,
                        choices=[("URBANA", "Urbana"), ("RURAL", "Rural")],
                        max_length=10,
                        null=True,
                        verbose_name="Zona de residencia",
                    ),
                ),
                (
                    "municipio_divipola",
                    models.CharField(
                        blank=True,
                        help_text="Código DANE del municipio de residencia (se completará con la tabla DIVIPOLA).",
                        max_length=8,
                        null=True,
                        verbose_name="Código DIVIPOLA municipio",
                    ),
                ),
                (
                    "departamento_divipola",
                    models.CharField(
                        blank=True,
                        max_length=5,
                        null=True,
                        verbose_name="Código DIVIPOLA departamento",
                    ),
                ),
                (
                    "regimen_salud",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CONTRIBUTIVO", "Contributivo"),
                            ("SUBSIDIADO", "Subsidiado"),
                            ("ESPECIAL", "Especial / Excepción"),
                            ("NO_AFILIADO", "No afiliado / Vinculado"),
                        ],
                        max_length=15,
                        null=True,
                        verbose_name="Régimen de salud",
                    ),
                ),
                (
                    "discapacidad_categoria",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NINGUNA", "Ninguna"),
                            ("FISICA", "Física (movilidad)"),
                            ("INTELECTUAL", "Intelectual / cognitiva"),
                            ("PSICOSOCIAL", "Psicosocial (mental)"),
                            ("VISUAL_BAJA", "Visual — baja visión"),
                            ("VISUAL_CEGUERA", "Visual — ceguera"),
                            ("AUDITIVA_HIPOACUSIA", "Auditiva — hipoacusia"),
                            ("AUDITIVA_SORDA", "Auditiva — sordera"),
                            ("SORDOCEGUERA", "Sordoceguera"),
                            ("MULTIPLE", "Múltiple"),
                            ("SISTEMICA", "Sistémica"),
                            ("VOZ_Y_HABLA", "De la voz y el habla"),
                            ("TEA", "Trastorno del espectro autista"),
                            ("OTRA", "Otra"),
                        ],
                        max_length=25,
                        null=True,
                        verbose_name="Categoría de discapacidad (MEN)",
                    ),
                ),
                (
                    "capacidad_excepcional",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NINGUNA", "Ninguna"),
                            ("GLOBAL", "Capacidad excepcional global"),
                            ("TALENTO_CIENTIFICO", "Talento científico/tecnológico"),
                            ("TALENTO_ARTISTICO", "Talento artístico"),
                            ("TALENTO_DEPORTIVO", "Talento deportivo"),
                            ("OTRA", "Otra"),
                        ],
                        max_length=25,
                        null=True,
                        verbose_name="Capacidad / talento excepcional",
                    ),
                ),
                (
                    "grupo_etnico",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NINGUNO", "Ninguno"),
                            ("INDIGENA", "Indígena"),
                            ("AFROCOLOMBIANO", "Afrocolombiano / negro"),
                            ("RAIZAL", "Raizal (San Andrés)"),
                            ("PALENQUERO", "Palenquero (San Basilio)"),
                            ("ROM", "ROM (gitano)"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Grupo étnico",
                    ),
                ),
                (
                    "estrato",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("0", "Sin estrato"),
                            ("1", "Estrato 1"),
                            ("2", "Estrato 2"),
                            ("3", "Estrato 3"),
                            ("4", "Estrato 4"),
                            ("5", "Estrato 5"),
                            ("6", "Estrato 6"),
                        ],
                        max_length=1,
                        null=True,
                        verbose_name="Estrato socioeconómico",
                    ),
                ),
                (
                    "sisben_grupo",
                    models.CharField(
                        blank=True,
                        help_text="Clasificación SISBÉN IV (ej: A1, B2, C3).",
                        max_length=10,
                        null=True,
                        verbose_name="Grupo SISBÉN",
                    ),
                ),
                (
                    "sisben_puntaje",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Puntaje SISBÉN",
                    ),
                ),
                (
                    "victima_conflicto",
                    models.BooleanField(
                        default=False, verbose_name="¿Víctima del conflicto armado?"
                    ),
                ),
                (
                    "tipo_poblacion_victima",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DESPLAZADO", "Desplazado"),
                            ("VICTIMA_MINAS", "Víctima de minas antipersona"),
                            ("DESVINCULADO", "Desvinculado de grupos armados"),
                            ("HIJO_DESMOVILIZADO", "Hijo de adulto desmovilizado"),
                            ("OTRA", "Otra"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Tipo de población víctima",
                    ),
                ),
                (
                    "srpa",
                    models.BooleanField(
                        default=False,
                        verbose_name="¿Sistema de Responsabilidad Penal Adolescente (SRPA)?",
                    ),
                ),
                (
                    "apoyo_academico_especial",
                    models.BooleanField(
                        default=False,
                        verbose_name="¿Requiere apoyo académico especial?",
                    ),
                ),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="caracterizaciones_estudiante",
                        to="finanzas.institucioneducativa",
                        verbose_name="Institución",
                    ),
                ),
            ],
            options={
                "verbose_name": "Caracterización de estudiante",
                "verbose_name_plural": "Caracterizaciones de estudiantes",
            },
        ),
    ]
