# Generated by Django 5.2.15 on 2026-06-20 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_academica", "0041_caracterizacionestudiante"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Logro",
        ),
    ]
