# Generated by Django 5.2.15 on 2026-06-20 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_academica", "0042_delete_logro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logropreescolar",
            name="materia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="logros_preescolar",
                to="gestion_academica.materia",
                verbose_name="Materia Asociada (opcional)",
            ),
        ),
    ]
