# Generated by Django 5.2.15 on 2026-06-20 14:14

from django.db import migrations, models


def asignar_orden_inicial(apps, schema_editor):
    """Asigna orden secuencial (1, 2, 3...) a las áreas existentes,
    por institución y alfabéticamente, para que no queden todas en 0."""
    AreaAcademica = apps.get_model("gestion_academica", "AreaAcademica")
    instituciones = (
        AreaAcademica.objects.values_list("institucion_id", flat=True).distinct()
    )
    for institucion_id in instituciones:
        areas = AreaAcademica.objects.filter(
            institucion_id=institucion_id
        ).order_by("nombre")
        for indice, area in enumerate(areas, start=1):
            area.orden = indice
            area.save(update_fields=["orden"])


def revertir_orden(apps, schema_editor):
    # No-op: el campo se elimina al revertir AddField.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_academica", "0043_alter_logropreescolar_materia"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="areaacademica",
            options={
                "ordering": ["orden", "nombre"],
                "verbose_name": "Área Académica",
                "verbose_name_plural": "Áreas Académicas",
            },
        ),
        migrations.AddField(
            model_name="areaacademica",
            name="orden",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Define el orden en que se muestran las áreas en pantallas y reportes (menor = primero).",
                verbose_name="Orden de aparición",
            ),
        ),
        migrations.RunPython(asignar_orden_inicial, revertir_orden),
    ]
