# Generated by Django 5.2.15 on 2026-06-20 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_academica", "0044_alter_areaacademica_options_areaacademica_orden"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EsquemaCalificacion",
        ),
    ]
