# Generated by Django 5.2.15 on 2026-07-01 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0022_pagoregistrado_pago_inst_fecha_idx"),
        ("gestion_academica", "0045_delete_esquemacalificacion"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="estudiante",
            index=models.Index(
                fields=["institucion", "activo"], name="estudiante_inst_activo_idx"
            ),
        ),
    ]
