# Generated by Django 5.2.15 on 2026-07-02 09:26

from django.db import migrations, models
from django.db.models.functions import TruncDate


def rellenar_fecha_solo(apps, schema_editor):
    """Rellena fecha_solo en registros históricos que lo tengan vacío.

    TruncDate convierte el DateTimeField a fecha en la zona horaria activa
    (America/Bogota, settings.TIME_ZONE) — el mismo criterio que usa
    RegistroAsistencia.save() con localtime(fecha).date().
    """
    RegistroAsistencia = apps.get_model("gestion_academica", "RegistroAsistencia")
    RegistroAsistencia.objects.filter(fecha_solo__isnull=True).update(
        fecha_solo=TruncDate("fecha")
    )


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0022_pagoregistrado_pago_inst_fecha_idx"),
        ("gestion_academica", "0046_estudiante_estudiante_inst_activo_idx"),
    ]

    operations = [
        migrations.RunPython(rellenar_fecha_solo, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="registroasistencia",
            name="fecha_solo",
            field=models.DateField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="registroasistencia",
            index=models.Index(
                fields=["institucion", "fecha_solo", "estado"],
                name="asistencia_inst_fecha_idx",
            ),
        ),
    ]
