# Generated by Django 5.2.1 on 2026-08-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_academica", "0073_tipo_documento_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="deber",
            name="audio",
            field=models.FileField(
                blank=True,
                help_text="Explicación en voz para el deber. Se puede transcribir con IA como subtítulo.",
                null=True,
                upload_to="deberes_audio/%Y/%m/",
                verbose_name="Audio de apoyo (explicación hablada, opcional)",
            ),
        ),
        migrations.AddField(
            model_name="deber",
            name="audio_transcripcion",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Subtítulo del audio para estudiantes sordos o con dificultad auditiva.",
                verbose_name="Transcripción del audio (IA)",
            ),
        ),
    ]
