# Generated by Django 5.2.1 on 2026-08-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_academica", "0074_audio_apoyo"),
    ]

    operations = [
        migrations.AddField(
            model_name="deber",
            name="descripcion_simple",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Versión simplificada de las instrucciones, generada con IA para apoyo a la lectura.",
                verbose_name="Descripción en lectura fácil (IA)",
            ),
        ),
        migrations.AddField(
            model_name="observacionboletin",
            name="observacion_simple",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Versión simplificada de la observación, generada con IA para apoyo a la lectura.",
                verbose_name="Observación en lectura fácil (IA)",
            ),
        ),
    ]
