# Generated by Django 5.2.1 on 2026-09-02 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0033_institucioneducativa_idiomas_contratados"),
        ("gestion_academica", "0077_usuario_idioma_aleman"),
    ]

    operations = [
        migrations.CreateModel(
            name="Enfasis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=100, verbose_name="Énfasis / Taller"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enfasis_tecnicos",
                        to="finanzas.institucioneducativa",
                        verbose_name="Institución",
                    ),
                ),
            ],
            options={
                "verbose_name": "Énfasis / Taller",
                "verbose_name_plural": "Énfasis / Talleres",
                "ordering": ["nombre"],
                "unique_together": {("institucion", "nombre")},
            },
        ),
        migrations.AddField(
            model_name="curso",
            name="enfasis",
            field=models.ForeignKey(
                blank=True,
                help_text="Vacío = aplica a todo el grado (comportamiento normal). Con un énfasis = solo ven y califican este curso los estudiantes con ese mismo énfasis (talleres técnicos).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cursos",
                to="gestion_academica.enfasis",
                verbose_name="Énfasis / Taller",
            ),
        ),
        migrations.AddField(
            model_name="estudiante",
            name="enfasis",
            field=models.ForeignKey(
                blank=True,
                help_text="Solo aplica en instituciones con modalidad técnica (ej. media técnica).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="estudiantes",
                to="gestion_academica.enfasis",
                verbose_name="Énfasis / Taller",
            ),
        ),
    ]
