# Generated by Django 5.2.1 on 2026-09-03 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_academica", "0097_seed_retos_steam_lote3"),
    ]

    operations = [
        migrations.AddField(
            model_name="asignacionsimulacionsteam",
            name="actividad_calificable",
            field=models.OneToOneField(
                blank=True,
                help_text="Se crea automáticamente al asignar, con la categoría de evaluación elegida, para que la simulación pondere en el boletín.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="asignacion_simulacion_steam",
                to="gestion_academica.actividadcalificable",
                verbose_name="Actividad calificable enlazada",
            ),
        ),
    ]
