# Generated by Django 5.2.17 on 2026-09-21 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0040_cuentaporcobrarestudiante_ultimo_recordatorio_pago_enviado"),
        ("gestion_academica", "0100_backfill_permisos_grupos_0039"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistorialMatriculaAnual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "año_escolar",
                    models.PositiveIntegerField(verbose_name="Año Escolar"),
                ),
                (
                    "origen",
                    models.CharField(
                        choices=[
                            ("MATRICULA", "Matrícula/inscripción"),
                            ("PROMOCION", "Promoción anual"),
                            ("INFERIDO", "Inferido de calificaciones (backfill)"),
                        ],
                        max_length=20,
                        verbose_name="Origen del registro",
                    ),
                ),
                (
                    "confianza_backfill",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ALTA", "Alta"),
                            ("DUDOSA", "Dudosa — revisar manualmente"),
                        ],
                        help_text="Se marca 'Dudosa' cuando se infirió automáticamente y el estudiante no tenía suficientes calificaciones ese año para determinar el grado con certeza.",
                        max_length=10,
                        verbose_name="Confianza (solo si es inferido)",
                    ),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historial_matricula",
                        to="gestion_academica.estudiante",
                        verbose_name="Estudiante",
                    ),
                ),
                (
                    "grado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historial_matricula",
                        to="gestion_academica.grado",
                        verbose_name="Grado cursado ese año",
                    ),
                ),
                (
                    "grupo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="historial_matricula",
                        to="gestion_academica.grupo",
                        verbose_name="Grupo/Sección",
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial_matricula_anual",
                        to="finanzas.institucioneducativa",
                        verbose_name="Institución",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de Matrícula Anual",
                "verbose_name_plural": "Historial de Matrícula Anual",
                "ordering": ["-año_escolar"],
                "unique_together": {("estudiante", "año_escolar")},
            },
        ),
    ]
