# Generated by Django 5.2.17 on 2026-09-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_academica", "0102_backfill_historial_matricula"),
    ]

    operations = [
        migrations.AddField(
            model_name="anotacionobservador",
            name="es_ciberacoso",
            field=models.BooleanField(
                default=False,
                help_text="Marcado automáticamente por la IA cuando la situación ocurre o se difunde por redes sociales, chats u otro medio digital (Decreto 0769 de 2026).",
                verbose_name="¿Canal digital / ciberacoso?",
            ),
        ),
        migrations.AddField(
            model_name="casoconvivencia",
            name="es_ciberacoso",
            field=models.BooleanField(
                default=False,
                help_text="Indica si el hecho ocurrió o se difundió por un medio digital (redes sociales, chats, mensajería). Requerido para la ruta de atención al ciberacoso del Decreto 0769 de 2026.",
                verbose_name="Canal digital / ciberacoso",
            ),
        ),
    ]
