# Generated by Django 5.2.1 on 2026-09-03 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("finanzas", "0034_seed_modulo_steam"),
        ("gestion_academica", "0097_seed_retos_steam_lote3"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EjercicioMath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "es_publica",
                    models.BooleanField(
                        default=False,
                        verbose_name="Público (catálogo de la plataforma)",
                    ),
                ),
                (
                    "nivel_dificultad",
                    models.CharField(
                        choices=[
                            ("BASICO", "Básico"),
                            ("MEDIO", "Medio"),
                            ("ALTO", "Alto"),
                        ],
                        default="BASICO",
                        max_length=10,
                        verbose_name="Nivel de dificultad",
                    ),
                ),
                ("enunciado", models.TextField(verbose_name="Enunciado")),
                (
                    "explicacion",
                    models.TextField(
                        blank=True, verbose_name="Explicación de la respuesta"
                    ),
                ),
                (
                    "fuente",
                    models.CharField(blank=True, max_length=200, verbose_name="Fuente"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ejercicios_math_creados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "dba",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ejercicios_math",
                        to="gestion_academica.dbapredefinido",
                        verbose_name="DBA",
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vacío = ejercicio público del catálogo de la plataforma.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ejercicios_math",
                        to="finanzas.institucioneducativa",
                        verbose_name="Institución",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ejercicio de Matemáticas",
                "verbose_name_plural": "Ejercicios de Matemáticas",
                "ordering": ["dba", "nivel_dificultad", "pk"],
            },
        ),
        migrations.CreateModel(
            name="OpcionEjercicioMath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "letra",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                        max_length=1,
                        verbose_name="Letra",
                    ),
                ),
                ("texto", models.CharField(max_length=300, verbose_name="Texto")),
                (
                    "es_correcta",
                    models.BooleanField(default=False, verbose_name="Es correcta"),
                ),
                (
                    "ejercicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opciones",
                        to="halu_math.ejerciciomath",
                    ),
                ),
            ],
            options={
                "verbose_name": "Opción de ejercicio",
                "verbose_name_plural": "Opciones de ejercicio",
                "ordering": ["letra"],
                "unique_together": {("ejercicio", "letra")},
            },
        ),
        migrations.CreateModel(
            name="IntentoEjercicioMath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "es_correcta",
                    models.BooleanField(default=False, verbose_name="Es correcta"),
                ),
                (
                    "nivel_en_el_momento",
                    models.CharField(
                        choices=[
                            ("BASICO", "Básico"),
                            ("MEDIO", "Medio"),
                            ("ALTO", "Alto"),
                        ],
                        max_length=10,
                        verbose_name="Nivel en el momento del intento",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "ejercicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="halu_math.ejerciciomath",
                        verbose_name="Ejercicio",
                    ),
                ),
                (
                    "estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intentos_math",
                        to="gestion_academica.estudiante",
                        verbose_name="Estudiante",
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intentos_math",
                        to="finanzas.institucioneducativa",
                        verbose_name="Institución",
                    ),
                ),
                (
                    "opcion_elegida",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="halu_math.opcionejerciciomath",
                        verbose_name="Opción elegida",
                    ),
                ),
            ],
            options={
                "verbose_name": "Intento de ejercicio",
                "verbose_name_plural": "Intentos de ejercicio",
                "ordering": ["-creado_en"],
            },
        ),
        migrations.CreateModel(
            name="DominioDBA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nivel_actual",
                    models.CharField(
                        choices=[
                            ("BASICO", "Básico"),
                            ("MEDIO", "Medio"),
                            ("ALTO", "Alto"),
                        ],
                        default="BASICO",
                        max_length=10,
                        verbose_name="Nivel actual",
                    ),
                ),
                (
                    "racha_actual",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Racha actual"
                    ),
                ),
                (
                    "racha_maxima",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Racha máxima"
                    ),
                ),
                (
                    "intentos_totales",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Intentos totales"
                    ),
                ),
                (
                    "aciertos_totales",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Aciertos totales"
                    ),
                ),
                (
                    "dominado",
                    models.BooleanField(default=False, verbose_name="Dominado"),
                ),
                (
                    "fecha_dominado",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de dominio"
                    ),
                ),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "dba",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_academica.dbapredefinido",
                        verbose_name="DBA",
                    ),
                ),
                (
                    "estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dominios_math",
                        to="gestion_academica.estudiante",
                        verbose_name="Estudiante",
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dominios_math",
                        to="finanzas.institucioneducativa",
                        verbose_name="Institución",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dominio de DBA",
                "verbose_name_plural": "Dominios de DBA",
                "ordering": ["dba", "estudiante"],
                "unique_together": {("estudiante", "dba")},
            },
        ),
    ]
