# Generated by Django 5.2.1 on 2026-09-03 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0035_seed_modulo_halu_math"),
        ("gestion_academica", "0097_seed_retos_steam_lote3"),
        ("halu_math", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntentoManipulativo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("RECTA_NUMERICA", "Recta numérica abierta"),
                            ("BLOQUES_BASE10", "Bloques de base 10"),
                        ],
                        max_length=20,
                        verbose_name="Manipulativo",
                    ),
                ),
                (
                    "es_correcta",
                    models.BooleanField(default=False, verbose_name="Es correcta"),
                ),
                (
                    "nivel_en_el_momento",
                    models.CharField(
                        choices=[
                            ("BASICO", "Básico"),
                            ("MEDIO", "Medio"),
                            ("ALTO", "Alto"),
                        ],
                        max_length=10,
                        verbose_name="Nivel en el momento del intento",
                    ),
                ),
                (
                    "parametros",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Reto planteado y respuesta dada, para poder auditar.",
                        verbose_name="Parámetros del reto",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "dba",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_academica.dbapredefinido",
                        verbose_name="DBA",
                    ),
                ),
                (
                    "estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intentos_manipulativo",
                        to="gestion_academica.estudiante",
                        verbose_name="Estudiante",
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intentos_manipulativo",
                        to="finanzas.institucioneducativa",
                        verbose_name="Institución",
                    ),
                ),
            ],
            options={
                "verbose_name": "Intento de manipulativo",
                "verbose_name_plural": "Intentos de manipulativo",
                "ordering": ["-creado_en"],
            },
        ),
    ]
