# Generated by Django 5.2.1 on 2026-09-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("halu_math", "0002_intentomanipulativo"),
    ]

    operations = [
        migrations.AddField(
            model_name="dominiodba",
            name="racha_fluida_actual",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Aciertos fluidos seguidos en el nivel Alto — junto con la racha normal, se exige para marcar el DBA como dominado (ver halu_math.motor.calcular_es_fluido).",
                verbose_name="Racha fluida actual",
            ),
        ),
        migrations.AddField(
            model_name="intentoejerciciomath",
            name="cambios_antes_de_enviar",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Cuántas opciones distintas se exploraron (hover) antes del clic final — señal de duda.",
                verbose_name="Cambios antes de enviar",
            ),
        ),
        migrations.AddField(
            model_name="intentoejerciciomath",
            name="es_fluido",
            field=models.BooleanField(
                default=True,
                help_text="Rápida y sin muchas dudas, según halu_math.motor.calcular_es_fluido.",
                verbose_name="Respuesta fluida",
            ),
        ),
        migrations.AddField(
            model_name="intentoejerciciomath",
            name="tiempo_respuesta_ms",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Desde que se mostró el ejercicio hasta que se envió la respuesta.",
                null=True,
                verbose_name="Tiempo de respuesta (ms)",
            ),
        ),
        migrations.AddField(
            model_name="intentomanipulativo",
            name="cambios_antes_de_enviar",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Cuántas veces se manipuló el widget (saltos, unidades, decenas) antes de comprobar — señal de duda.",
                verbose_name="Cambios antes de enviar",
            ),
        ),
        migrations.AddField(
            model_name="intentomanipulativo",
            name="es_fluido",
            field=models.BooleanField(
                default=True,
                help_text="Rápida y sin muchas dudas, según halu_math.motor.calcular_es_fluido.",
                verbose_name="Respuesta fluida",
            ),
        ),
        migrations.AddField(
            model_name="intentomanipulativo",
            name="tiempo_respuesta_ms",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Desde que se mostró el reto hasta que se envió la respuesta.",
                null=True,
                verbose_name="Tiempo de respuesta (ms)",
            ),
        ),
    ]
