# Generated by Django 5.2.17 on 2026-09-16 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0036_seed_modulo_presupuesto"),
        ("gestion_academica", "0100_backfill_permisos_grupos_0039"),
        ("halu_math", "0004_seed_banco_publico_basico"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActividadHaluMath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "actividad",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="halu_math",
                        to="gestion_academica.actividadcalificable",
                        verbose_name="Actividad calificable",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actividades_halu_math_creadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "dbas",
                    models.ManyToManyField(
                        related_name="actividades_halu_math",
                        to="gestion_academica.dbapredefinido",
                        verbose_name="DBA a dominar",
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actividades_halu_math",
                        to="finanzas.institucioneducativa",
                        verbose_name="Institución",
                    ),
                ),
            ],
            options={
                "verbose_name": "Actividad de Halu Math",
                "verbose_name_plural": "Actividades de Halu Math",
            },
        ),
    ]
