# Generated by Django 5.2.17 on 2026-09-20 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_academica", "0100_backfill_permisos_grupos_0039"),
        ("halu_math", "0005_actividadhalumath"),
    ]

    operations = [
        migrations.AddField(
            model_name="actividadhalumath",
            name="item_malla",
            field=models.ForeignKey(
                blank=True,
                help_text="El logro de la malla curricular del colegio que esta actividad evalúa — lo que realmente se reporta en el boletín.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="actividades_halu_math",
                to="gestion_academica.itemmalla",
                verbose_name="Ítem de malla (logro) vinculado",
            ),
        ),
    ]
